--
-- Host: localhost    Database: majormud
-- ------------------------------------------------------
--

CREATE DATABASE IF NOT EXISTS `majormud`
	DEFAULT CHARACTER SET ascii
	DEFAULT COLLATE ascii_general_ci;

USE `majormud`;

--
-- Table structure for table `abilities`
--

DROP TABLE IF EXISTS `abilities`;
CREATE TABLE `abilities` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`number` int(11) NOT NULL,
	`name` varchar(50) NOT NULL,
	`color` int(8) NOT NULL,
	`description` varchar(255) NOT NULL,
	`script_id` int(11) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `number` (`number`),
	UNIQUE KEY `name` (`name`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `actions`
--

DROP TABLE IF EXISTS `actions`;
CREATE TABLE `actions` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`Name` varchar(29) NOT NULL,
	`SingleToUser` varchar(79) NOT NULL,
	`SingleToRoom` varchar(79) NOT NULL,
	`UserToUser` varchar(79) NOT NULL,
	`UserToOtherUser` varchar(79) NOT NULL,
	`UserToRoom` varchar(79) NOT NULL,
	`MonsterToUser` varchar(79) NOT NULL,
	`MonsterToRoom` varchar(79) NOT NULL,
	`InventoryToUser` varchar(79) NOT NULL,
	`InventoryToRoom` varchar(79) NOT NULL,
	`FloorItemToUser` varchar(79) NOT NULL,
	`FloorItemToRoom` varchar(79) NOT NULL,
	`Offset` tinyint NOT NULL,
	`Blank` varchar(98) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `Name` (`Name`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `banks`
--

DROP TABLE IF EXISTS `banks`;
CREATE TABLE `banks` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`BBSName` varchar(32) NOT NULL,
	`ShopNumber` int NOT NULL,
	`Cash` int NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `BBSName` (`BBSName`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `classes`
--

DROP TABLE IF EXISTS `classes`;
CREATE TABLE `classes` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`number` smallint NOT NULL,
	`name` varchar(29) NOT NULL,
	`minhp` smallint NOT NULL,
	`maxhp` smallint NOT NULL,
	`exp` smallint NOT NULL,
	`nothing1` smallint NOT NULL,
	`nothing2` smallint NOT NULL,
	`nothing3` smallint NOT NULL,
	`abila1` smallint NOT NULL,
	`abila2` smallint NOT NULL,
	`abila3` smallint NOT NULL,
	`abila4` smallint NOT NULL,
	`abila5` smallint NOT NULL,
	`abila6` smallint NOT NULL,
	`abila7` smallint NOT NULL,
	`abila8` smallint NOT NULL,
	`abila9` smallint NOT NULL,
	`abila10` smallint NOT NULL,
	`magictype` smallint NOT NULL,
	`magiclvl` smallint NOT NULL,
	`weapon` smallint NOT NULL,
	`armor` smallint NOT NULL,
	`combat` smallint NOT NULL,
	`abilb1` smallint NOT NULL,
	`abilb2` smallint NOT NULL,
	`abilb3` smallint NOT NULL,
	`abilb4` smallint NOT NULL,
	`abilb5` smallint NOT NULL,
	`abilb6` smallint NOT NULL,
	`abilb7` smallint NOT NULL,
	`abilb8` smallint NOT NULL,
	`abilb9` smallint NOT NULL,
	`abilb10` smallint NOT NULL,
	`nothing4` smallint NOT NULL,
	`nothing5` smallint NOT NULL,
	`nothing6` smallint NOT NULL,
	`titletext` int NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `number` (`number`),
	UNIQUE KEY `name` (`name`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `gangs`
--

DROP TABLE IF EXISTS `gangs`;
CREATE TABLE `gangs` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`KeyName` varchar(19) NOT NULL,
	`DisplayName` varchar(19) NOT NULL,
	`Exp` bigint NOT NULL,
	`Leader` varchar(29) NOT NULL,
	`DateCreated` int NOT NULL,
	`Members` smallint NOT NULL,
	`unknown2` int NOT NULL,
	`unknown3` int NOT NULL,
	`RollOver` int NOT NULL,
	`RollTimes` smallint NOT NULL,
	`unknown5` varchar(161) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `KeyName` (`KeyName`),
	UNIQUE KEY `Leader` (`Leader`),
	KEY `DisplayName` (`DisplayName`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `items`
--

DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`Number` int NOT NULL,
	`unknown1` smallint NOT NULL,
	`GameLimit` smallint NOT NULL,
	`unknown2` smallint NOT NULL,
	`unknown3` smallint NOT NULL,
	`unknown4` smallint NOT NULL,
	`unknown5` smallint NOT NULL,
	`EmptySpace1` varchar(156) NOT NULL,
	`Name` varchar(29) NOT NULL,
	`Desc1` varchar(60) NOT NULL,
	`Desc2` varchar(60) NOT NULL,
	`Desc3` varchar(60) NOT NULL,
	`Desc4` varchar(60) NOT NULL,
	`Desc5` varchar(60) NOT NULL,
	`Desc6` varchar(60) NOT NULL,
	`Desc7` varchar(60) NOT NULL,
	`Desc8` varchar(60) NOT NULL,
	`Desc9` varchar(60) NOT NULL,
	`unknown6` smallint NOT NULL,
	`Weight` smallint NOT NULL,
	`Type` smallint NOT NULL,
	`AbilityA1` smallint NOT NULL,
	`AbilityA2` smallint NOT NULL,
	`AbilityA3` smallint NOT NULL,
	`AbilityA4` smallint NOT NULL,
	`AbilityA5` smallint NOT NULL,
	`AbilityA6` smallint NOT NULL,
	`AbilityA7` smallint NOT NULL,
	`AbilityA8` smallint NOT NULL,
	`AbilityA9` smallint NOT NULL,
	`AbilityA10` smallint NOT NULL,
	`AbilityA11` smallint NOT NULL,
	`AbilityA12` smallint NOT NULL,
	`AbilityA13` smallint NOT NULL,
	`AbilityA14` smallint NOT NULL,
	`AbilityA15` smallint NOT NULL,
	`AbilityA16` smallint NOT NULL,
	`AbilityA17` smallint NOT NULL,
	`AbilityA18` smallint NOT NULL,
	`AbilityA19` smallint NOT NULL,
	`AbilityA20` smallint NOT NULL,
	`Uses` smallint NOT NULL,
	`unknown7` smallint NOT NULL,
	`Cost` smallint NOT NULL,
	`Class1` smallint NOT NULL,
	`Class2` smallint NOT NULL,
	`Class3` smallint NOT NULL,
	`Class4` smallint NOT NULL,
	`Class5` smallint NOT NULL,
	`Class6` smallint NOT NULL,
	`Class7` smallint NOT NULL,
	`Class8` smallint NOT NULL,
	`Class9` smallint NOT NULL,
	`Class10` smallint NOT NULL,
	`unknown8` smallint NOT NULL,
	`unknown9` smallint NOT NULL,
	`unknown10` smallint NOT NULL,
	`Minhit` smallint NOT NULL,
	`Maxhit` smallint NOT NULL,
	`AC` smallint NOT NULL,
	`Race1` smallint NOT NULL,
	`Race2` smallint NOT NULL,
	`Race3` smallint NOT NULL,
	`Race4` smallint NOT NULL,
	`Race5` smallint NOT NULL,
	`Race6` smallint NOT NULL, 
	`Race7` smallint NOT NULL,
	`Race8` smallint NOT NULL,
	`Race9` smallint NOT NULL,
	`Race10` smallint NOT NULL,
	`unknown111` smallint NOT NULL,
	`unknown112` smallint NOT NULL,
	`unknown113` smallint NOT NULL,
	`unknown114` smallint NOT NULL,
	`unknown115` smallint NOT NULL,
	`unknown116` smallint NOT NULL,
	`unknown117` smallint NOT NULL,
	`unknown118` smallint NOT NULL,
	`unknown119` smallint NOT NULL,
	`unknown1110` smallint NOT NULL,
	`Negate1` smallint NOT NULL,
	`Negate2` smallint NOT NULL,
	`Negate3` smallint NOT NULL,
	`Negate4` smallint NOT NULL,
	`Negate5` smallint NOT NULL,
	`Negate6` smallint NOT NULL,
	`Negate7` smallint NOT NULL,
	`Negate8` smallint NOT NULL,
	`Negate9` smallint NOT NULL,
	`Negate10` smallint NOT NULL,
	`Negate11` smallint NOT NULL,
	`Negate12` smallint NOT NULL,
	`Negate13` smallint NOT NULL,
	`Negate14` smallint NOT NULL,
	`Negate15` smallint NOT NULL,
	`Negate16` smallint NOT NULL,
	`Negate17` smallint NOT NULL,
	`Negate18` smallint NOT NULL,
	`Negate19` smallint NOT NULL,
	`Negate20` smallint NOT NULL,
	`Weapon` smallint NOT NULL,
	`Armour` smallint NOT NULL,
	`WornOn` smallint NOT NULL,
	`Accuracy` smallint NOT NULL,
	`DR` smallint NOT NULL,
	`Gettable` tinyint NOT NULL,
	`unknown12` tinyint NOT NULL,
	`ReqStr` smallint NOT NULL,
	`unknown13a1` smallint NOT NULL,
	`unknown13a2` smallint NOT NULL,
	`unknown13a3` smallint NOT NULL,
	`unknown13a4` smallint NOT NULL,
	`unknown13a5` smallint NOT NULL,
	`OpenRunic` int NOT NULL,
	`OpenPlatinum` int NOT NULL,
	`OpenGold` int NOT NULL,
	`OpenSilver` int NOT NULL,
	`OpenCopper` int NOT NULL,
	`unknown13b1` smallint NOT NULL,
	`unknown13b2` smallint NOT NULL,
	`unknown13b3` smallint NOT NULL,
	`unknown13b4` smallint NOT NULL,
	`unknown13b5` smallint NOT NULL,
	`unknown13b6` smallint NOT NULL,
	`unknown13b7` smallint NOT NULL,
	`unknown13b8` smallint NOT NULL,
	`unknown13b9` smallint NOT NULL,
	`unknown13b10` smallint NOT NULL,
	`unknown13b11` smallint NOT NULL,
	`unknown13b12` smallint NOT NULL,
	`unknown13b13` smallint NOT NULL,
	`unknown13b14` smallint NOT NULL, 
	`unknown13b15` smallint NOT NULL,
	`Speed` smallint NOT NULL,
	`unknown14` smallint NOT NULL,
	`AbilityB1` smallint NOT NULL,
	`AbilityB2` smallint NOT NULL,
	`AbilityB3` smallint NOT NULL,
	`AbilityB4` smallint NOT NULL,
	`AbilityB5` smallint NOT NULL,
	`AbilityB6` smallint NOT NULL,
	`AbilityB7` smallint NOT NULL,
	`AbilityB8` smallint NOT NULL,
	`AbilityB9` smallint NOT NULL,
	`AbilityB10` smallint NOT NULL,
	`AbilityB11` smallint NOT NULL,
	`AbilityB12` smallint NOT NULL,
	`AbilityB13` smallint NOT NULL,
	`AbilityB14` smallint NOT NULL,
	`AbilityB15` smallint NOT NULL,
	`AbilityB16` smallint NOT NULL,
	`AbilityB17` smallint NOT NULL,
	`AbilityB18` smallint NOT NULL,
	`AbilityB19` smallint NOT NULL,
	`AbilityB20` smallint NOT NULL,
	`unknown15` smallint NOT NULL,
	`HitMsg` int NOT NULL,
	`MissMsg` int NOT NULL,
	`ReadTB` int NOT NULL,
	`DistructMsg` int NOT NULL,
	`unknown161` smallint NOT NULL,
	`unknown162` smallint NOT NULL,
	`unknown163` smallint NOT NULL,
	`unknown164` smallint NOT NULL,
	`unknown165` smallint NOT NULL,
	`unknown166` smallint NOT NULL,
	`NotDroppable` tinyint NOT NULL,
	`CostType` tinyint NOT NULL,
	`RetainAfterUses` tinyint NOT NULL,
	`Robable` tinyint NOT NULL,
	`DestroyOnDeath` tinyint NOT NULL,
	`unknown19` tinyint NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `Number` (`Number`),
	KEY `Name` (`Name`),
	KEY `Type` (`Type`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `limiteds`
--

DROP TABLE IF EXISTS `limiteds`;
CREATE TABLE `limiteds` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`recnum` int NOT NULL,
	`itemnum` int NOT NULL,
	`offset` int NOT NULL,
	`mapnum` int NOT NULL,
	`roomnum` int NOT NULL,
	`username` varchar(29) NOT NULL,
	`unknown2` smallint NOT NULL,
	`monnum` int NOT NULL,
	`unknown3` varchar(15) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `recnum` (`recnum`),
	UNIQUE KEY `itemnum` (`itemnum`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `messages`
--

DROP TABLE IF EXISTS `messages`;
CREATE TABLE `messages` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`Number` int NOT NULL,
	`MsgLine1` varchar(81) NOT NULL,
	`MsgLine2` varchar(81) NOT NULL,
	`MsgLine3` varchar(81) NOT NULL,
	`Offset` int NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `Number` (`Number`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `monsters`
--

DROP TABLE IF EXISTS `monsters`;
CREATE TABLE `monsters` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`Number` int NOT NULL,
	`EmptySpace` varchar(49) NOT NULL,
	`Name` varchar(28) NOT NULL,
	`nothing1` tinyint NOT NULL,
	`Groupp` smallint NOT NULL,
	`nothingXX1` smallint NOT NULL,
	`ExpMulti` int NOT NULL,
	`Indexx` smallint NOT NULL,
	`nothingXX3` smallint NOT NULL,
	`Something2` int NOT NULL,
	`WeaponNumber` int NOT NULL,
	`DR` smallint NOT NULL,
	`AC` smallint NOT NULL,
	`Something3` smallint NOT NULL,
	`Follow` smallint NOT NULL,
	`MR` smallint NOT NULL,
	`BSDefence` smallint NOT NULL,
	`Experience` int NOT NULL,
	`Hitpoints` smallint NOT NULL,
	`Energy` smallint NOT NULL,
	`HPRegen` smallint NOT NULL,
	`AbilityA1` smallint NOT NULL,
	`AbilityA2` smallint NOT NULL,
	`AbilityA3` smallint NOT NULL,
	`AbilityA4` smallint NOT NULL,
	`AbilityA5` smallint NOT NULL,
	`AbilityA6` smallint NOT NULL,
	`AbilityA7` smallint NOT NULL,
	`AbilityA8` smallint NOT NULL,
	`AbilityA9` smallint NOT NULL,
	`AbilityA10` smallint NOT NULL,
	`AbilityB1` smallint NOT NULL,
	`AbilityB2` smallint NOT NULL,
	`AbilityB3` smallint NOT NULL,
	`AbilityB4` smallint NOT NULL,
	`AbilityB5` smallint NOT NULL,
	`AbilityB6` smallint NOT NULL,
	`AbilityB7` smallint NOT NULL,
	`AbilityB8` smallint NOT NULL,
	`AbilityB9` smallint NOT NULL,
	`AbilityB10` smallint NOT NULL,
	`GameLimit` smallint NOT NULL,
	`Active` smallint NOT NULL,
	`Type` smallint NOT NULL,
	`nothing2` tinyint NOT NULL,
	`Undead` tinyint NOT NULL,
	`Alignment` smallint NOT NULL,
	`nothing3` smallint NOT NULL,
	`RegenTime` smallint NOT NULL,
	`DateKilled` smallint NOT NULL,
	`TimeKilled` smallint NOT NULL,
	`MoveMsg` int NOT NULL,
	`DeathMsg` int NOT NULL,
	`ItemNumber1` int NOT NULL,
	`ItemNumber2` int NOT NULL,
	`ItemNumber3` int NOT NULL,
	`ItemNumber4` int NOT NULL,
	`ItemNumber5` int NOT NULL,
	`ItemNumber6` int NOT NULL,
	`ItemNumber7` int NOT NULL,
	`ItemNumber8` int NOT NULL,
	`ItemNumber9` int NOT NULL,
	`ItemNumber10` int NOT NULL,
	`ItemUses1` smallint NOT NULL,
	`ItemUses2` smallint NOT NULL,
	`ItemUses3` smallint NOT NULL,
	`ItemUses4` smallint NOT NULL,
	`ItemUses5` smallint NOT NULL,
	`ItemUses6` smallint NOT NULL,
	`ItemUses7` smallint NOT NULL,
	`ItemUses8` smallint NOT NULL,
	`ItemUses9` smallint NOT NULL,
	`ItemUses10` smallint NOT NULL,
	`ItemDropPer1` tinyint NOT NULL,
	`ItemDropPer2` tinyint NOT NULL,
	`ItemDropPer3` tinyint NOT NULL,
	`ItemDropPer4` tinyint NOT NULL,
	`ItemDropPer5` tinyint NOT NULL,
	`ItemDropPer6` tinyint NOT NULL,
	`ItemDropPer7` tinyint NOT NULL,
	`ItemDropPer8` tinyint NOT NULL,
	`ItemDropPer9` tinyint NOT NULL,
	`ItemDropPer10` tinyint NOT NULL,
	`nothing9` smallint NOT NULL,
	`Runic` int NOT NULL,
	`Platinum` int NOT NULL,
	`Gold` int NOT NULL,
	`Silver` int NOT NULL,
	`Copper` int NOT NULL,
	`GreetTxt` int NOT NULL,
	`CharmLvL` smallint NOT NULL,
	`Nothing16` smallint NOT NULL,
	`DescTxt` int NOT NULL,
	`AttackType1` tinyint NOT NULL,
	`AttackType2` tinyint NOT NULL,
	`AttackType3` tinyint NOT NULL,
	`AttackType4` tinyint NOT NULL,
	`AttackType5` tinyint NOT NULL,
	`Nothing22` tinyint NOT NULL,
	`AttackAccuSpell1` smallint NOT NULL,
	`AttackAccuSpell2` smallint NOT NULL,
	`AttackAccuSpell3` smallint NOT NULL,
	`AttackAccuSpell4` smallint NOT NULL,
	`AttackAccuSpell5` smallint NOT NULL,
	`AttackPer1` tinyint NOT NULL,
	`AttackPer2` tinyint NOT NULL,
	`AttackPer3` tinyint NOT NULL,
	`AttackPer4` tinyint NOT NULL,
	`AttackPer5` tinyint NOT NULL,
	`Nothing17` tinyint NOT NULL,
	`AttackMinHCastPer1` smallint NOT NULL,
	`AttackMinHCastPer2` smallint NOT NULL,
	`AttackMinHCastPer3` smallint NOT NULL,
	`AttackMinHCastPer4` smallint NOT NULL,
	`AttackMinHCastPer5` smallint NOT NULL,
	`AttackMaxHCastLvl1` smallint NOT NULL,
	`AttackMaxHCastLvl2` smallint NOT NULL,
	`AttackMaxHCastLvl3` smallint NOT NULL,
	`AttackMaxHCastLvl4` smallint NOT NULL,
	`AttackMaxHCastLvl5` smallint NOT NULL,
	`Nothing18` smallint NOT NULL,
	`AttackHitMsg1` int NOT NULL,
	`AttackHitMsg2` int NOT NULL,
	`AttackHitMsg3` int NOT NULL,
	`AttackHitMsg4` int NOT NULL,
	`AttackHitMsg5` int NOT NULL,
	`AttackDodgeMsg1` int NOT NULL,
	`AttackDodgeMsg2` int NOT NULL,
	`AttackDodgeMsg3` int NOT NULL,
	`AttackDodgeMsg4` int NOT NULL,
	`AttackDodgeMsg5` int NOT NULL,
	`AttackMissMsg1` int NOT NULL,
	`AttackMissMsg2` int NOT NULL,
	`AttackMissMsg3` int NOT NULL,
	`AttackMissMsg4` int NOT NULL,
	`AttackMissMsg5` int NOT NULL,
	`AttackEnergy1` smallint NOT NULL,
	`AttackEnergy2` smallint NOT NULL,
	`AttackEnergy3` smallint NOT NULL,
	`AttackEnergy4` smallint NOT NULL,
	`AttackEnergy5` smallint NOT NULL,
	`Nothing19` smallint NOT NULL,
	`TalkTxt` int NOT NULL,
	`CharmRes` smallint NOT NULL,
	`Nothing21` smallint NOT NULL,
	`AttackHitSpell1` smallint NOT NULL,
	`AttackHitSpell2` smallint NOT NULL,
	`AttackHitSpell3` smallint NOT NULL,
	`AttackHitSpell4` smallint NOT NULL,
	`AttackHitSpell5` smallint NOT NULL,
	`DeathSpellNumber` smallint NOT NULL,
	`Nothing23` smallint NOT NULL,
	`Nothing24` smallint NOT NULL,
	`Nothing25` smallint NOT NULL,
	`Nothing26` smallint NOT NULL,
	`Nothing27` smallint NOT NULL,
	`Nothing28` smallint NOT NULL,
	`Nothing29` smallint NOT NULL,
	`CreateSpellNumber` smallint NOT NULL,
	`SpellNumber1` smallint NOT NULL,
	`SpellNumber2` smallint NOT NULL,
	`SpellNumber3` smallint NOT NULL,
	`SpellNumber4` smallint NOT NULL,
	`SpellNumber5` smallint NOT NULL,
	`SpellCastPer1` tinyint NOT NULL,
	`SpellCastPer2` tinyint NOT NULL,
	`SpellCastPer3` tinyint NOT NULL,
	`SpellCastPer4` tinyint NOT NULL,
	`SpellCastPer5` tinyint NOT NULL,
	`SpellCastLvl1` tinyint NOT NULL,
	`SpellCastLvl2` tinyint NOT NULL,
	`SpellCastLvl3` tinyint NOT NULL,
	`SpellCastLvl4` tinyint NOT NULL,
	`SpellCastLvl5` tinyint NOT NULL,
	`DescLine1` varchar(70) NOT NULL,
	`DescLine2` varchar(70) NOT NULL,
	`DescLine3` varchar(70) NOT NULL,
	`DescLine4` varchar(70) NOT NULL,
	`Gender` tinyint NOT NULL,
	`Nothing14` tinyint NOT NULL,
	`Nothing15` smallint NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `Number` (`Number`),
	KEY `Name` (`Name`),
	KEY `RegenTime` (`RegenTime`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `races`
--

DROP TABLE IF EXISTS `races`;
CREATE TABLE `races` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`number` smallint NOT NULL,
	`name` varchar(29) NOT NULL,
	`minint` smallint NOT NULL,
	`minwil` smallint NOT NULL,
	`minstr` smallint NOT NULL,
	`minhea` smallint NOT NULL,
	`minagi` smallint NOT NULL,
	`minchm` smallint NOT NULL,
	`hpbonus` smallint NOT NULL,
	`nothing1` int NOT NULL,
	`abila1` smallint NOT NULL,
	`abila2` smallint NOT NULL,
	`abila3` smallint NOT NULL,
	`abila4` smallint NOT NULL,
	`abila5` smallint NOT NULL,
	`abila6` smallint NOT NULL,
	`abila7` smallint NOT NULL,
	`abila8` smallint NOT NULL,
	`abila9` smallint NOT NULL,
	`abila10` smallint NOT NULL,
	`cp` smallint NOT NULL,
	`abilb1` smallint NOT NULL,
	`abilb2` smallint NOT NULL,
	`abilb3` smallint NOT NULL,
	`abilb4` smallint NOT NULL,
	`abilb5` smallint NOT NULL,
	`abilb6` smallint NOT NULL,
	`abilb7` smallint NOT NULL,
	`abilb8` smallint NOT NULL,
	`abilb9` smallint NOT NULL,
	`abilb10` smallint NOT NULL,
	`nothing2` int NOT NULL,
	`nothing3` smallint NOT NULL,
	`expchart` smallint NOT NULL,
	`nothing4` smallint NOT NULL,
	`maxint` smallint NOT NULL,
	`maxwil` smallint NOT NULL,
	`maxstr` smallint NOT NULL,
	`maxhea` smallint NOT NULL,
	`maxagi` smallint NOT NULL,
	`maxchm` smallint NOT NULL,
	`nothing5` int NOT NULL,
	`nothing6` int NOT NULL,
	`nothing7` int NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `number` (`number`),
	UNIQUE KEY `name` (`name`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `rooms`
--

DROP TABLE IF EXISTS `rooms`;
CREATE TABLE `rooms` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`MapNumber` int NOT NULL,
	`RoomNumber` int NOT NULL,
	`EmptySpace` varchar(252) NOT NULL,
	`Name` varchar(52) NOT NULL,
	`Desc1` varchar(70) NOT NULL,
	`Desc2` varchar(70) NOT NULL,
	`Desc3` varchar(70) NOT NULL,
	`Desc4` varchar(70) NOT NULL,
	`Desc5` varchar(70) NOT NULL,
	`Desc6` varchar(70) NOT NULL,
	`Desc7` varchar(70) NOT NULL,
	`AnsiMap` varchar(12) NOT NULL,
	`RoomExit1` int NOT NULL,
	`RoomExit2` int NOT NULL,
	`RoomExit3` int NOT NULL,
	`RoomExit4` int NOT NULL,
	`RoomExit5` int NOT NULL,
	`RoomExit6` int NOT NULL,
	`RoomExit7` int NOT NULL,
	`RoomExit8` int NOT NULL,
	`RoomExit9` int NOT NULL,
	`RoomExit10` int NOT NULL,
	`RoomType1` smallint NOT NULL,
	`RoomType2` smallint NOT NULL,
	`RoomType3` smallint NOT NULL,
	`RoomType4` smallint NOT NULL,
	`RoomType5` smallint NOT NULL,
	`RoomType6` smallint NOT NULL,
	`RoomType7` smallint NOT NULL,
	`RoomType8` smallint NOT NULL,
	`RoomType9` smallint NOT NULL,
	`RoomType10` smallint NOT NULL,
	`Para11` int NOT NULL,
	`Para12` int NOT NULL,
	`Para13` int NOT NULL,
	`Para14` int NOT NULL,
	`Para15` int NOT NULL,
	`Para16` int NOT NULL,
	`Para17` int NOT NULL,
	`Para18` int NOT NULL,
	`Para19` int NOT NULL,
	`Para110` int NOT NULL,
	`Para21` smallint NOT NULL,
	`Para22` smallint NOT NULL,
	`Para23` smallint NOT NULL,
	`Para24` smallint NOT NULL,
	`Para25` smallint NOT NULL,
	`Para26` smallint NOT NULL,
	`Para27` smallint NOT NULL,
	`Para28` smallint NOT NULL,
	`Para29` smallint NOT NULL,
	`Para210` smallint NOT NULL,
	`Para31` int NOT NULL,
	`Para32` int NOT NULL,
	`Para33` int NOT NULL,
	`Para34` int NOT NULL,
	`Para35` int NOT NULL,
	`Para36` int NOT NULL,
	`Para37` int NOT NULL,
	`Para38` int NOT NULL,
	`Para39` int NOT NULL,
	`Para310` int NOT NULL,
	`Para41` int NOT NULL,
	`Para42` int NOT NULL,
	`Para43` int NOT NULL,
	`Para44` int NOT NULL,
	`Para45` int NOT NULL,
	`Para46` int NOT NULL,
	`Para47` int NOT NULL,
	`Para48` int NOT NULL,
	`Para49` int NOT NULL,
	`Para410` int NOT NULL,
	`CurrentRoomMon1` int NOT NULL,
	`CurrentRoomMon2` int NOT NULL,
	`CurrentRoomMon3` int NOT NULL,
	`CurrentRoomMon4` int NOT NULL,
	`CurrentRoomMon5` int NOT NULL,
	`CurrentRoomMon6` int NOT NULL,
	`CurrentRoomMon7` int NOT NULL,
	`CurrentRoomMon8` int NOT NULL,
	`CurrentRoomMon9` int NOT NULL,
	`CurrentRoomMon10` int NOT NULL,
	`CurrentRoomMon11` int NOT NULL,
	`CurrentRoomMon12` int NOT NULL,
	`CurrentRoomMon13` int NOT NULL,
	`CurrentRoomMon14` int NOT NULL,
	`CurrentRoomMon15` int NOT NULL,
	`Type` smallint NOT NULL,
	`NewSpot` smallint NOT NULL,
	`ShopNum` int NOT NULL,
	`nothing1111` smallint NOT NULL,
	`nothing12` smallint NOT NULL,
	`nothing13` smallint NOT NULL,
	`nothing14` smallint NOT NULL,
	`nothing15` smallint NOT NULL,
	`nothing16` smallint NOT NULL,
	`nothing17` smallint NOT NULL,
	`nothing18` smallint NOT NULL,
	`nothing19` smallint NOT NULL,
	`nothing110` smallint NOT NULL,
	`nothing111` smallint NOT NULL,
	`nothing112` smallint NOT NULL,
	`nothing113` smallint NOT NULL,
	`nothing114` smallint NOT NULL,
	`nothing115` smallint NOT NULL,
	`MinIndex` smallint NOT NULL,
	`MaxIndex` smallint NOT NULL,
	`ByNumber` int NOT NULL,
	`dontknow` smallint NOT NULL,
	`Light` smallint NOT NULL,
	`GangHouseNumber` smallint NOT NULL,
	`RoomItems1` int NOT NULL,
	`RoomItems2` int NOT NULL,
	`RoomItems3` int NOT NULL,
	`RoomItems4` int NOT NULL,
	`RoomItems5` int NOT NULL,
	`RoomItems6` int NOT NULL,
	`RoomItems7` int NOT NULL,
	`RoomItems8` int NOT NULL,
	`RoomItems9` int NOT NULL,
	`RoomItems10` int NOT NULL,
	`RoomItems11` int NOT NULL,
	`RoomItems12` int NOT NULL,
	`RoomItems13` int NOT NULL,
	`RoomItems14` int NOT NULL,
	`RoomItems15` int NOT NULL,
	`RoomItems16` int NOT NULL,
	`RoomItems17` int NOT NULL,
	`RoomItemUses1` smallint NOT NULL,
	`RoomItemUses2` smallint NOT NULL,
	`RoomItemUses3` smallint NOT NULL,
	`RoomItemUses4` smallint NOT NULL,
	`RoomItemUses5` smallint NOT NULL,
	`RoomItemUses6` smallint NOT NULL,
	`RoomItemUses7` smallint NOT NULL,
	`RoomItemUses8` smallint NOT NULL,
	`RoomItemUses9` smallint NOT NULL,
	`RoomItemUses10` smallint NOT NULL,
	`RoomItemUses11` smallint NOT NULL,
	`RoomItemUses12` smallint NOT NULL,
	`RoomItemUses13` smallint NOT NULL,
	`RoomItemUses14` smallint NOT NULL,
	`RoomItemUses15` smallint NOT NULL,
	`RoomItemUses16` smallint NOT NULL,
	`RoomItemUses17` smallint NOT NULL,
	`nothing4` smallint NOT NULL,
	`InvisItems1` int NOT NULL,
	`InvisItems2` int NOT NULL,
	`InvisItems3` int NOT NULL,
	`InvisItems4` int NOT NULL,
	`InvisItems5` int NOT NULL,
	`InvisItems6` int NOT NULL,
	`InvisItems7` int NOT NULL,
	`InvisItems8` int NOT NULL,
	`InvisItems9` int NOT NULL,
	`InvisItems10` int NOT NULL,
	`InvisItems11` int NOT NULL,
	`InvisItems12` int NOT NULL,
	`InvisItems13` int NOT NULL,
	`InvisItems14` int NOT NULL,
	`InvisItems15` int NOT NULL,
	`InvisItemUses1` smallint NOT NULL,
	`InvisItemUses2` smallint NOT NULL,
	`InvisItemUses3` smallint NOT NULL,
	`InvisItemUses4` smallint NOT NULL,
	`InvisItemUses5` smallint NOT NULL,
	`InvisItemUses6` smallint NOT NULL,
	`InvisItemUses7` smallint NOT NULL,
	`InvisItemUses8` smallint NOT NULL,
	`InvisItemUses9` smallint NOT NULL,
	`InvisItemUses10` smallint NOT NULL,
	`InvisItemUses11` smallint NOT NULL,
	`InvisItemUses12` smallint NOT NULL,
	`InvisItemUses13` smallint NOT NULL,
	`InvisItemUses14` smallint NOT NULL,
	`InvisItemUses15` smallint NOT NULL,
	`nothing5` smallint NOT NULL,
	`Runic` int NOT NULL,
	`Platinum` int NOT NULL,
	`Gold` int NOT NULL,
	`Silver` int NOT NULL,
	`Copper` int NOT NULL,
	`nothing71` int NOT NULL,
	`nothing72` int NOT NULL,
	`nothing73` int NOT NULL,
	`nothing74` int NOT NULL,
	`nothing75` int NOT NULL,
	`MaxRegen` int NOT NULL,
	`MonsterType` smallint NOT NULL,
	`unknown69` smallint NOT NULL,
	`Attributes` int NOT NULL,
	`nothing9` int NOT NULL,
	`DeathRoom` int NOT NULL,
	`ExitRoom` int NOT NULL,
	`RoomItemQty1` smallint NOT NULL,
	`RoomItemQty2` smallint NOT NULL,
	`RoomItemQty3` smallint NOT NULL,
	`RoomItemQty4` smallint NOT NULL,
	`RoomItemQty5` smallint NOT NULL,
	`RoomItemQty6` smallint NOT NULL,
	`RoomItemQty7` smallint NOT NULL,
	`RoomItemQty8` smallint NOT NULL,
	`RoomItemQty9` smallint NOT NULL,
	`RoomItemQty10` smallint NOT NULL,
	`RoomItemQty11` smallint NOT NULL,
	`RoomItemQty12` smallint NOT NULL,
	`RoomItemQty13` smallint NOT NULL,
	`RoomItemQty14` smallint NOT NULL,
	`RoomItemQty15` smallint NOT NULL,
	`RoomItemQty16` smallint NOT NULL,
	`RoomItemQty17` smallint NOT NULL,
	`InvisItemQty1` smallint NOT NULL,
	`InvisItemQty2` smallint NOT NULL,
	`InvisItemQty3` smallint NOT NULL,
	`InvisItemQty4` smallint NOT NULL,
	`InvisItemQty5` smallint NOT NULL,
	`InvisItemQty6` smallint NOT NULL,
	`InvisItemQty7` smallint NOT NULL,
	`InvisItemQty8` smallint NOT NULL,
	`InvisItemQty9` smallint NOT NULL,
	`InvisItemQty10` smallint NOT NULL,
	`InvisItemQty11` smallint NOT NULL,
	`InvisItemQty12` smallint NOT NULL,
	`InvisItemQty13` smallint NOT NULL,
	`InvisItemQty14` smallint NOT NULL,
	`InvisItemQty15` smallint NOT NULL,
	`CmdText` int NOT NULL,
	`nothing10` int NOT NULL,
	`Delay` smallint NOT NULL,
	`MaxArea` smallint NOT NULL,
	`Nothing11` int NOT NULL,
	`ControlRoom` int NOT NULL,
	`PermNPC` int NOT NULL,
	`PlacedItems1` int NOT NULL,
	`PlacedItems2` int NOT NULL,
	`PlacedItems3` int NOT NULL,
	`PlacedItems4` int NOT NULL,
	`PlacedItems5` int NOT NULL,
	`PlacedItems6` int NOT NULL,
	`PlacedItems7` int NOT NULL,
	`PlacedItems8` int NOT NULL,
	`PlacedItems9` int NOT NULL,
	`PlacedItems10` int NOT NULL,
	`Nothing121` int NOT NULL,
	`Nothing122` int NOT NULL,
	`Something1` int NOT NULL,
	`Spell` int NOT NULL,
	`unknown70` smallint NOT NULL,
	`NumMons` tinyint NOT NULL,
	`unknown71` tinyint NOT NULL,
	PRIMARY KEY (`id`),
	KEY `MapNumber` (`MapNumber`),
	KEY `RoomNumber` (`RoomNumber`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `shops`
--

DROP TABLE IF EXISTS `shops`;
CREATE TABLE `shops` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`Number` int NOT NULL,
	`Name` varchar(38) NOT NULL,
	`ShopAfterName` smallint NOT NULL,
	`ShopDescriptionA` varchar(52) NOT NULL,
	`ShopDescriptionB` varchar(52) NOT NULL,
	`ShopDescriptionC` varchar(52) NOT NULL,
	`ShopType` smallint NOT NULL,
	`ShopMinLvL` smallint NOT NULL,
	`ShopMaxLvl` smallint NOT NULL,
	`ShopMarkUp` smallint NOT NULL,
	`ShopNothing4` smallint NOT NULL,
	`ShopClassLimit` tinyint NOT NULL,
	`ShopNothingAA` tinyint NOT NULL,
	`ShopItemNumber1` int NOT NULL,
	`ShopItemNumber2` int NOT NULL,
	`ShopItemNumber3` int NOT NULL,
	`ShopItemNumber4` int NOT NULL,
	`ShopItemNumber5` int NOT NULL,
	`ShopItemNumber6` int NOT NULL,
	`ShopItemNumber7` int NOT NULL,
	`ShopItemNumber8` int NOT NULL,
	`ShopItemNumber9` int NOT NULL,
	`ShopItemNumber10` int NOT NULL,
	`ShopItemNumber11` int NOT NULL,
	`ShopItemNumber12` int NOT NULL,
	`ShopItemNumber13` int NOT NULL,
	`ShopItemNumber14` int NOT NULL,
	`ShopItemNumber15` int NOT NULL,
	`ShopItemNumber16` int NOT NULL,
	`ShopItemNumber17` int NOT NULL,
	`ShopItemNumber18` int NOT NULL,
	`ShopItemNumber19` int NOT NULL,
	`ShopItemNumber20` int NOT NULL,
	`ShopMax1` smallint NOT NULL,
	`ShopMax2` smallint NOT NULL,
	`ShopMax3` smallint NOT NULL,
	`ShopMax4` smallint NOT NULL,
	`ShopMax5` smallint NOT NULL,
	`ShopMax6` smallint NOT NULL,
	`ShopMax7` smallint NOT NULL,
	`ShopMax8` smallint NOT NULL,
	`ShopMax9` smallint NOT NULL,
	`ShopMax10` smallint NOT NULL,
	`ShopMax11` smallint NOT NULL,
	`ShopMax12` smallint NOT NULL,
	`ShopMax13` smallint NOT NULL,
	`ShopMax14` smallint NOT NULL,
	`ShopMax15` smallint NOT NULL,
	`ShopMax16` smallint NOT NULL,
	`ShopMax17` smallint NOT NULL,
	`ShopMax18` smallint NOT NULL,
	`ShopMax19` smallint NOT NULL,
	`ShopMax20` smallint NOT NULL,
	`ShopNow1` smallint NOT NULL,
	`ShopNow2` smallint NOT NULL,
	`ShopNow3` smallint NOT NULL,
	`ShopNow4` smallint NOT NULL,
	`ShopNow5` smallint NOT NULL,
	`ShopNow6` smallint NOT NULL,
	`ShopNow7` smallint NOT NULL,
	`ShopNow8` smallint NOT NULL,
	`ShopNow9` smallint NOT NULL,
	`ShopNow10` smallint NOT NULL,
	`ShopNow11` smallint NOT NULL,
	`ShopNow12` smallint NOT NULL,
	`ShopNow13` smallint NOT NULL,
	`ShopNow14` smallint NOT NULL,
	`ShopNow15` smallint NOT NULL,
	`ShopNow16` smallint NOT NULL,
	`ShopNow17` smallint NOT NULL,
	`ShopNow18` smallint NOT NULL,
	`ShopNow19` smallint NOT NULL,
	`ShopNow20` smallint NOT NULL,
	`ShopRgnTime1` smallint NOT NULL,
	`ShopRgnTime2` smallint NOT NULL,
	`ShopRgnTime3` smallint NOT NULL,
	`ShopRgnTime4` smallint NOT NULL,
	`ShopRgnTime5` smallint NOT NULL,
	`ShopRgnTime6` smallint NOT NULL,
	`ShopRgnTime7` smallint NOT NULL,
	`ShopRgnTime8` smallint NOT NULL,
	`ShopRgnTime9` smallint NOT NULL,
	`ShopRgnTime10` smallint NOT NULL,
	`ShopRgnTime11` smallint NOT NULL,
	`ShopRgnTime12` smallint NOT NULL,
	`ShopRgnTime13` smallint NOT NULL,
	`ShopRgnTime14` smallint NOT NULL,
	`ShopRgnTime15` smallint NOT NULL,
	`ShopRgnTime16` smallint NOT NULL,
	`ShopRgnTime17` smallint NOT NULL,
	`ShopRgnTime18` smallint NOT NULL,
	`ShopRgnTime19` smallint NOT NULL,
	`ShopRgnTime20` smallint NOT NULL,
	`ShopRgnNumber1` smallint NOT NULL,
	`ShopRgnNumber2` smallint NOT NULL,
	`ShopRgnNumber3` smallint NOT NULL,
	`ShopRgnNumber4` smallint NOT NULL,
	`ShopRgnNumber5` smallint NOT NULL,
	`ShopRgnNumber6` smallint NOT NULL,
	`ShopRgnNumber7` smallint NOT NULL,
	`ShopRgnNumber8` smallint NOT NULL,
	`ShopRgnNumber9` smallint NOT NULL,
	`ShopRgnNumber10` smallint NOT NULL,
	`ShopRgnNumber11` smallint NOT NULL,
	`ShopRgnNumber12` smallint NOT NULL,
	`ShopRgnNumber13` smallint NOT NULL,
	`ShopRgnNumber14` smallint NOT NULL,
	`ShopRgnNumber15` smallint NOT NULL,
	`ShopRgnNumber16` smallint NOT NULL,
	`ShopRgnNumber17` smallint NOT NULL,
	`ShopRgnNumber18` smallint NOT NULL,
	`ShopRgnNumber19` smallint NOT NULL,
	`ShopRgnNumber20` smallint NOT NULL,
	`ShopRgnPercentage1` tinyint NOT NULL,
	`ShopRgnPercentage2` tinyint NOT NULL,
	`ShopRgnPercentage3` tinyint NOT NULL,
	`ShopRgnPercentage4` tinyint NOT NULL,
	`ShopRgnPercentage5` tinyint NOT NULL,
	`ShopRgnPercentage6` tinyint NOT NULL,
	`ShopRgnPercentage7` tinyint NOT NULL,
	`ShopRgnPercentage8` tinyint NOT NULL,
	`ShopRgnPercentage9` tinyint NOT NULL,
	`ShopRgnPercentage10` tinyint NOT NULL,
	`ShopRgnPercentage11` tinyint NOT NULL,
	`ShopRgnPercentage12` tinyint NOT NULL,
	`ShopRgnPercentage13` tinyint NOT NULL,
	`ShopRgnPercentage14` tinyint NOT NULL,
	`ShopRgnPercentage15` tinyint NOT NULL,
	`ShopRgnPercentage16` tinyint NOT NULL,
	`ShopRgnPercentage17` tinyint NOT NULL,
	`ShopRgnPercentage18` tinyint NOT NULL,
	`ShopRgnPercentage19` tinyint NOT NULL,
	`ShopRgnPercentage20` tinyint NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `Number` (`Number`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `spells`
--

DROP TABLE IF EXISTS `spells`;
CREATE TABLE `spells` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`number` smallint NOT NULL,
	`name` varchar(29) NOT NULL,
	`desca` varchar(50) NOT NULL,
	`descb` varchar(50) NOT NULL,
	`n01` smallint NOT NULL,
	`castmsga` int NOT NULL,
	`n021` smallint NOT NULL,
	`n022` smallint NOT NULL,
	`n023` smallint NOT NULL,
	`n024` smallint NOT NULL,
	`n025` smallint NOT NULL,
	`n026` smallint NOT NULL,
	`n027` smallint NOT NULL,
	`n028` smallint NOT NULL,
	`n029` smallint NOT NULL,
	`n0210` smallint NOT NULL,
	`n0211` smallint NOT NULL,
	`lvlcap` tinyint NOT NULL,
	`n03` tinyint NOT NULL,
	`msgstyle` tinyint NOT NULL,
	`n041` tinyint NOT NULL,
	`n042` tinyint NOT NULL,
	`n043` tinyint NOT NULL,
	`abilb1` smallint NOT NULL,
	`abilb2` smallint NOT NULL,
	`abilb3` smallint NOT NULL,
	`abilb4` smallint NOT NULL,
	`abilb5` smallint NOT NULL,
	`abilb6` smallint NOT NULL,
	`abilb7` smallint NOT NULL,
	`abilb8` smallint NOT NULL,
	`abilb9` smallint NOT NULL,
	`abilb10` smallint NOT NULL,
	`energy` smallint NOT NULL,
	`levell` smallint NOT NULL,
	`minn` smallint NOT NULL,
	`maxx` smallint NOT NULL,
	`spelltype` smallint NOT NULL,
	`typeofresists` smallint NOT NULL,
	`difficulty` smallint NOT NULL,
	`n05` smallint NOT NULL,
	`target` smallint NOT NULL,
	`duration` smallint NOT NULL,
	`typeofattack` smallint NOT NULL,
	`n06` smallint NOT NULL,
	`resistability` smallint NOT NULL,
	`magerya` smallint NOT NULL,
	`abila1` smallint NOT NULL,
	`abila2` smallint NOT NULL,
	`abila3` smallint NOT NULL,
	`abila4` smallint NOT NULL,
	`abila5` smallint NOT NULL,
	`abila6` smallint NOT NULL,
	`abila7` smallint NOT NULL,
	`abila8` smallint NOT NULL,
	`abila9` smallint NOT NULL,
	`abila10` smallint NOT NULL,
	`castmsgb` int NOT NULL,
	`mana` smallint NOT NULL,
	`maxincrease` tinyint NOT NULL,
	`lvlsmaxincrease` tinyint NOT NULL,
	`mageryb` smallint NOT NULL,
	`minincrease` tinyint NOT NULL,
	`lvlsminincrease` tinyint NOT NULL,
	`durincrease` tinyint NOT NULL,
	`lvlsdurincrease` tinyint NOT NULL,
	`shortname` varchar(5) NOT NULL,
	`n07` int NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `number` (`number`),
	KEY `name` (`name`),
	KEY `shortname` (`shortname`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `textblocks`
--

DROP TABLE IF EXISTS `textblocks`;
CREATE TABLE `textblocks` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`PartNum` smallint NOT NULL,
	`LeadIn1` tinyint NOT NULL,
	`LeadIn2` tinyint NOT NULL,
	`LeadIn3` tinyint NOT NULL,
	`LeadIn4` tinyint NOT NULL,
	`LeadIn5` tinyint NOT NULL,
	`LeadIn6` tinyint NOT NULL,
	`LeadIn7` tinyint NOT NULL,
	`LeadIn8` tinyint NOT NULL,
	`LeadIn9` tinyint NOT NULL,
	`LeadIn10` tinyint NOT NULL,
	`LeadIn11` tinyint NOT NULL,
	`LeadIn12` tinyint NOT NULL,
	`LeadIn13` tinyint NOT NULL,
	`LeadIn14` tinyint NOT NULL,
	`Number` int NOT NULL,
	`LinkTo` int NOT NULL,
	`Data1` varchar(128) NOT NULL,
	`Data2` varchar(128) NOT NULL,
	`Data3` varchar(128) NOT NULL,
	`Data4` varchar(128) NOT NULL, 
	`Data5` varchar(128) NOT NULL,
	`Data6` varchar(128) NOT NULL,
	`Data7` varchar(128) NOT NULL, 
	`Data8` varchar(128) NOT NULL,
	`Data9` varchar(128) NOT NULL,
	`Data10` varchar(128) NOT NULL, 
	`Data11` varchar(128) NOT NULL,
	`Data12` varchar(128) NOT NULL,
	`Data13` varchar(128) NOT NULL, 
	`Data14` varchar(128) NOT NULL,
	`Data15` varchar(128) NOT NULL,
	`Data16` varchar(79) NOT NULL,
	PRIMARY KEY (`id`),
	KEY `Number` (`Number`),
	KEY `PartNum` (`PartNum`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `updates`
--

DROP TABLE IF EXISTS `updates`;
CREATE TABLE `updates` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`RecordLength` smallint NOT NULL,
	`PageSizee` smallint NOT NULL,
	`IndexCount` tinyint NOT NULL,
	`FileVersion` tinyint NOT NULL,
	`Reserved1` tinyint NOT NULL,
	`Reserved2` tinyint NOT NULL,
	`Reserved3` tinyint NOT NULL,
	`Reserved4` tinyint NOT NULL,
	`FileFlags` smallint NOT NULL,
	`DuplicatePointCount` tinyint NOT NULL,
	`NotUsed` tinyint NOT NULL,
	`Allocation` smallint NOT NULL,
	`KeyPosition` smallint NOT NULL,
	`KeyLength` smallint NOT NULL,
	`KeyFlags` smallint NOT NULL,
	`Reserved21` tinyint NOT NULL,
	`Reserved22` tinyint NOT NULL,
	`Reserved23` tinyint NOT NULL,
	`Reserved24` tinyint NOT NULL,
	`ExtDataType` tinyint NOT NULL,
	`NullValue` tinyint NOT NULL,
	`NotUsed21` tinyint NOT NULL,
	`NotUsed22` tinyint NOT NULL,
	`ManKeyNumber` tinyint NOT NULL,
	`ACSNumber` tinyint NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `RecordLength` (`RecordLength`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`BBSName` varchar(32) NOT NULL,
	`FirstName` varchar(10) NOT NULL,
	`LastName` varchar(18) NOT NULL,
	`NotExperience` int NOT NULL,
	`Buff1` smallint NOT NULL,
	`Buff2` smallint NOT NULL,
	`Buff3` smallint NOT NULL,
	`Buff4` smallint NOT NULL,
	`Buff5` smallint NOT NULL,
	`Buff6` smallint NOT NULL,
	`Buff7` smallint NOT NULL,
	`Buff8` smallint NOT NULL,
	`Buff9` smallint NOT NULL,
	`Buff10` smallint NOT NULL,
	`BuffValue1` smallint NOT NULL,
	`BuffValue2` smallint NOT NULL,
	`BuffValue3` smallint NOT NULL,
	`BuffValue4` smallint NOT NULL,
	`BuffValue5` smallint NOT NULL,
	`BuffValue6` smallint NOT NULL,
	`BuffValue7` smallint NOT NULL,
	`BuffValue8` smallint NOT NULL,
	`BuffValue9` smallint NOT NULL,
	`BuffValue10` smallint NOT NULL,
	`BuffRoundsLeft1` smallint NOT NULL,
	`BuffRoundsLeft2` smallint NOT NULL,
	`BuffRoundsLeft3` smallint NOT NULL,
	`BuffRoundsLeft4` smallint NOT NULL,
	`BuffRoundsLeft5` smallint NOT NULL,
	`BuffRoundsLeft6` smallint NOT NULL,
	`BuffRoundsLeft7` smallint NOT NULL,
	`BuffRoundsLeft8` smallint NOT NULL,
	`BuffRoundsLeft9` smallint NOT NULL,
	`BuffRoundsLeft10` smallint NOT NULL,
	`Title` varchar(19) NOT NULL,
	`Race` smallint NOT NULL,
	`Class` smallint NOT NULL,
	`Level` smallint NOT NULL,
	`INTE` smallint NOT NULL,
	`WIL` smallint NOT NULL,
	`STR` smallint NOT NULL,
	`HEA` smallint NOT NULL,
	`AGI` smallint NOT NULL,
	`CHA` smallint NOT NULL,
	`INTEcurr` smallint NOT NULL,
	`WILcurr` smallint NOT NULL,
	`STRcurr` smallint NOT NULL,
	`HEAcurr` smallint NOT NULL,
	`AGIcurr` smallint NOT NULL,
	`CHAcurr` smallint NOT NULL,
	`HPMax` smallint NOT NULL,
	`HPcurr` smallint NOT NULL,
	`ENCMax` smallint NOT NULL,
	`ENCcurr` smallint NOT NULL,
	`Energy1` smallint NOT NULL,
	`Energy2` smallint NOT NULL,
	`Energy3` smallint NOT NULL,
	`unknown11` smallint NOT NULL,
	`unknown12` smallint NOT NULL,
	`MagicResMax` smallint NOT NULL,
	`MagicResCurr` smallint NOT NULL,
	`MapNumber` int NOT NULL,
	`RoomNum` int NOT NULL,
	`nothing2` smallint NOT NULL,
	`unknown21` smallint NOT NULL,
	`unknown22` smallint NOT NULL,
	`nothing3` smallint NOT NULL,
	`unknown31` tinyint NOT NULL,
	`unknown32` tinyint NOT NULL,
	`nothing4` smallint NOT NULL,
	`Item0` int NOT NULL,
	`Item1` int NOT NULL,
	`Item2` int NOT NULL,
	`Item3` int NOT NULL,
	`Item4` int NOT NULL,
	`Item5` int NOT NULL,
	`Item6` int NOT NULL,
	`Item7` int NOT NULL,
	`Item8` int NOT NULL,
	`Item9` int NOT NULL,
	`Item10` int NOT NULL,
	`Item11` int NOT NULL,
	`Item12` int NOT NULL,
	`Item13` int NOT NULL,
	`Item14` int NOT NULL,
	`Item15` int NOT NULL,
	`Item16` int NOT NULL,
	`Item17` int NOT NULL,
	`Item18` int NOT NULL,
	`Item19` int NOT NULL,
	`Item20` int NOT NULL,
	`Item21` int NOT NULL,
	`Item22` int NOT NULL,
	`Item23` int NOT NULL,
	`Item24` int NOT NULL,
	`Item25` int NOT NULL,
	`Item26` int NOT NULL,
	`Item27` int NOT NULL,
	`Item28` int NOT NULL,
	`Item29` int NOT NULL,
	`Item30` int NOT NULL,
	`Item31` int NOT NULL,
	`Item32` int NOT NULL,
	`Item33` int NOT NULL,
	`Item34` int NOT NULL,
	`Item35` int NOT NULL,
	`Item36` int NOT NULL,
	`Item37` int NOT NULL,
	`Item38` int NOT NULL,
	`Item39` int NOT NULL,
	`Item40` int NOT NULL,
	`Item41` int NOT NULL,
	`Item42` int NOT NULL,
	`Item43` int NOT NULL,
	`Item44` int NOT NULL,
	`Item45` int NOT NULL,
	`Item46` int NOT NULL,
	`Item47` int NOT NULL,
	`Item48` int NOT NULL,
	`Item49` int NOT NULL,
	`Item50` int NOT NULL,
	`Item51` int NOT NULL,
	`Item52` int NOT NULL,
	`Item53` int NOT NULL,
	`Item54` int NOT NULL,
	`Item55` int NOT NULL,
	`Item56` int NOT NULL,
	`Item57` int NOT NULL,
	`Item58` int NOT NULL,
	`Item59` int NOT NULL,
	`Item60` int NOT NULL,
	`Item61` int NOT NULL,
	`Item62` int NOT NULL,
	`Item63` int NOT NULL,
	`Item64` int NOT NULL,
	`Item65` int NOT NULL,
	`Item66` int NOT NULL,
	`Item67` int NOT NULL,
	`Item68` int NOT NULL,
	`Item69` int NOT NULL,
	`Item70` int NOT NULL,
	`Item71` int NOT NULL,
	`Item72` int NOT NULL,
	`Item73` int NOT NULL,
	`Item74` int NOT NULL,
	`Item75` int NOT NULL,
	`Item76` int NOT NULL,
	`Item77` int NOT NULL,
	`Item78` int NOT NULL,
	`Item79` int NOT NULL,
	`Item80` int NOT NULL,
	`Item81` int NOT NULL,
	`Item82` int NOT NULL,
	`Item83` int NOT NULL,
	`Item84` int NOT NULL,
	`Item85` int NOT NULL,
	`Item86` int NOT NULL,
	`Item87` int NOT NULL,
	`Item88` int NOT NULL,
	`Item89` int NOT NULL,
	`Item90` int NOT NULL,
	`Item91` int NOT NULL,
	`Item92` int NOT NULL,
	`Item93` int NOT NULL,
	`Item94` int NOT NULL,
	`Item95` int NOT NULL,
	`Item96` int NOT NULL,
	`Item97` int NOT NULL,
	`Item98` int NOT NULL,
	`Item99` int NOT NULL,
	`ItemUse0` smallint NOT NULL,
	`ItemUse1` smallint NOT NULL,
	`ItemUse2` smallint NOT NULL,
	`ItemUse3` smallint NOT NULL,
	`ItemUse4` smallint NOT NULL,
	`ItemUse5` smallint NOT NULL,
	`ItemUse6` smallint NOT NULL,
	`ItemUse7` smallint NOT NULL,
	`ItemUse8` smallint NOT NULL,
	`ItemUse9` smallint NOT NULL,
	`ItemUse10` smallint NOT NULL,
	`ItemUse11` smallint NOT NULL,
	`ItemUse12` smallint NOT NULL,
	`ItemUse13` smallint NOT NULL,
	`ItemUse14` smallint NOT NULL,
	`ItemUse15` smallint NOT NULL,
	`ItemUse16` smallint NOT NULL,
	`ItemUse17` smallint NOT NULL,
	`ItemUse18` smallint NOT NULL,
	`ItemUse19` smallint NOT NULL,
	`ItemUse20` smallint NOT NULL,
	`ItemUse21` smallint NOT NULL,
	`ItemUse22` smallint NOT NULL,
	`ItemUse23` smallint NOT NULL,
	`ItemUse24` smallint NOT NULL,
	`ItemUse25` smallint NOT NULL,
	`ItemUse26` smallint NOT NULL,
	`ItemUse27` smallint NOT NULL,
	`ItemUse28` smallint NOT NULL,
	`ItemUse29` smallint NOT NULL,
	`ItemUse30` smallint NOT NULL,
	`ItemUse31` smallint NOT NULL,
	`ItemUse32` smallint NOT NULL,
	`ItemUse33` smallint NOT NULL,
	`ItemUse34` smallint NOT NULL,
	`ItemUse35` smallint NOT NULL,
	`ItemUse36` smallint NOT NULL,
	`ItemUse37` smallint NOT NULL,
	`ItemUse38` smallint NOT NULL,
	`ItemUse39` smallint NOT NULL,
	`ItemUse40` smallint NOT NULL,
	`ItemUse41` smallint NOT NULL,
	`ItemUse42` smallint NOT NULL,
	`ItemUse43` smallint NOT NULL,
	`ItemUse44` smallint NOT NULL,
	`ItemUse45` smallint NOT NULL,
	`ItemUse46` smallint NOT NULL,
	`ItemUse47` smallint NOT NULL,
	`ItemUse48` smallint NOT NULL,
	`ItemUse49` smallint NOT NULL,
	`ItemUse50` smallint NOT NULL,
	`ItemUse51` smallint NOT NULL,
	`ItemUse52` smallint NOT NULL,
	`ItemUse53` smallint NOT NULL,
	`ItemUse54` smallint NOT NULL,
	`ItemUse55` smallint NOT NULL,
	`ItemUse56` smallint NOT NULL,
	`ItemUse57` smallint NOT NULL,
	`ItemUse58` smallint NOT NULL,
	`ItemUse59` smallint NOT NULL,
	`ItemUse60` smallint NOT NULL,
	`ItemUse61` smallint NOT NULL,
	`ItemUse62` smallint NOT NULL,
	`ItemUse63` smallint NOT NULL,
	`ItemUse64` smallint NOT NULL,
	`ItemUse65` smallint NOT NULL,
	`ItemUse66` smallint NOT NULL,
	`ItemUse67` smallint NOT NULL,
	`ItemUse68` smallint NOT NULL,
	`ItemUse69` smallint NOT NULL,
	`ItemUse70` smallint NOT NULL,
	`ItemUse71` smallint NOT NULL,
	`ItemUse72` smallint NOT NULL,
	`ItemUse73` smallint NOT NULL,
	`ItemUse74` smallint NOT NULL,
	`ItemUse75` smallint NOT NULL,
	`ItemUse76` smallint NOT NULL,
	`ItemUse77` smallint NOT NULL,
	`ItemUse78` smallint NOT NULL,
	`ItemUse79` smallint NOT NULL,
	`ItemUse80` smallint NOT NULL,
	`ItemUse81` smallint NOT NULL,
	`ItemUse82` smallint NOT NULL,
	`ItemUse83` smallint NOT NULL,
	`ItemUse84` smallint NOT NULL,
	`ItemUse85` smallint NOT NULL,
	`ItemUse86` smallint NOT NULL,
	`ItemUse87` smallint NOT NULL,
	`ItemUse88` smallint NOT NULL,
	`ItemUse89` smallint NOT NULL,
	`ItemUse90` smallint NOT NULL,
	`ItemUse91` smallint NOT NULL,
	`ItemUse92` smallint NOT NULL,
	`ItemUse93` smallint NOT NULL,
	`ItemUse94` smallint NOT NULL,
	`ItemUse95` smallint NOT NULL,
	`ItemUse96` smallint NOT NULL,
	`ItemUse97` smallint NOT NULL,
	`ItemUse98` smallint NOT NULL,
	`ItemUse99` smallint NOT NULL,
	`nothing5` int NOT NULL,
	`ItemKey0` int NOT NULL,
	`ItemKey1` int NOT NULL,
	`ItemKey2` int NOT NULL,
	`ItemKey3` int NOT NULL,
	`ItemKey4` int NOT NULL,
	`ItemKey5` int NOT NULL,
	`ItemKey6` int NOT NULL,
	`ItemKey7` int NOT NULL,
	`ItemKey8` int NOT NULL,
	`ItemKey9` int NOT NULL,
	`ItemKey10` int NOT NULL,
	`ItemKey11` int NOT NULL,
	`ItemKey12` int NOT NULL,
	`ItemKey13` int NOT NULL,
	`ItemKey14` int NOT NULL,
	`ItemKey15` int NOT NULL,
	`ItemKey16` int NOT NULL,
	`ItemKey17` int NOT NULL,
	`ItemKey18` int NOT NULL,
	`ItemKey19` int NOT NULL,
	`ItemKey20` int NOT NULL,
	`ItemKey21` int NOT NULL,
	`ItemKey22` int NOT NULL,
	`ItemKey23` int NOT NULL,
	`ItemKey24` int NOT NULL,
	`ItemKey25` int NOT NULL,
	`ItemKey26` int NOT NULL,
	`ItemKey27` int NOT NULL,
	`ItemKey28` int NOT NULL,
	`ItemKey29` int NOT NULL,
	`ItemKey30` int NOT NULL,
	`ItemKey31` int NOT NULL,
	`ItemKey32` int NOT NULL,
	`ItemKey33` int NOT NULL,
	`ItemKey34` int NOT NULL,
	`ItemKey35` int NOT NULL,
	`ItemKey36` int NOT NULL,
	`ItemKey37` int NOT NULL,
	`ItemKey38` int NOT NULL,
	`ItemKey39` int NOT NULL,
	`ItemKey40` int NOT NULL,
	`ItemKey41` int NOT NULL,
	`ItemKey42` int NOT NULL,
	`ItemKey43` int NOT NULL,
	`ItemKey44` int NOT NULL,
	`ItemKey45` int NOT NULL,
	`ItemKey46` int NOT NULL,
	`ItemKey47` int NOT NULL,
	`ItemKey48` int NOT NULL,
	`ItemKey49` int NOT NULL,
	`ItemKeyUse0` smallint NOT NULL,
	`ItemKeyUse1` smallint NOT NULL,
	`ItemKeyUse2` smallint NOT NULL,
	`ItemKeyUse3` smallint NOT NULL,
	`ItemKeyUse4` smallint NOT NULL,
	`ItemKeyUse5` smallint NOT NULL,
	`ItemKeyUse6` smallint NOT NULL,
	`ItemKeyUse7` smallint NOT NULL,
	`ItemKeyUse8` smallint NOT NULL,
	`ItemKeyUse9` smallint NOT NULL,
	`ItemKeyUse10` smallint NOT NULL,
	`ItemKeyUse11` smallint NOT NULL,
	`ItemKeyUse12` smallint NOT NULL,
	`ItemKeyUse13` smallint NOT NULL,
	`ItemKeyUse14` smallint NOT NULL,
	`ItemKeyUse15` smallint NOT NULL,
	`ItemKeyUse16` smallint NOT NULL,
	`ItemKeyUse17` smallint NOT NULL,
	`ItemKeyUse18` smallint NOT NULL,
	`ItemKeyUse19` smallint NOT NULL,
	`ItemKeyUse20` smallint NOT NULL,
	`ItemKeyUse21` smallint NOT NULL,
	`ItemKeyUse22` smallint NOT NULL,
	`ItemKeyUse23` smallint NOT NULL,
	`ItemKeyUse24` smallint NOT NULL,
	`ItemKeyUse25` smallint NOT NULL,
	`ItemKeyUse26` smallint NOT NULL,
	`ItemKeyUse27` smallint NOT NULL,
	`ItemKeyUse28` smallint NOT NULL,
	`ItemKeyUse29` smallint NOT NULL,
	`ItemKeyUse30` smallint NOT NULL,
	`ItemKeyUse31` smallint NOT NULL,
	`ItemKeyUse32` smallint NOT NULL,
	`ItemKeyUse33` smallint NOT NULL,
	`ItemKeyUse34` smallint NOT NULL,
	`ItemKeyUse35` smallint NOT NULL,
	`ItemKeyUse36` smallint NOT NULL,
	`ItemKeyUse37` smallint NOT NULL,
	`ItemKeyUse38` smallint NOT NULL,
	`ItemKeyUse39` smallint NOT NULL,
	`ItemKeyUse40` smallint NOT NULL,
	`ItemKeyUse41` smallint NOT NULL,
	`ItemKeyUse42` smallint NOT NULL,
	`ItemKeyUse43` smallint NOT NULL,
	`ItemKeyUse44` smallint NOT NULL,
	`ItemKeyUse45` smallint NOT NULL,
	`ItemKeyUse46` smallint NOT NULL,
	`ItemKeyUse47` smallint NOT NULL,
	`ItemKeyUse48` smallint NOT NULL,
	`ItemKeyUse49` smallint NOT NULL,
	`unknown41` int NOT NULL,
	`unknown42` int NOT NULL,
	`unknown43` int NOT NULL,
	`unknown44` int NOT NULL,
	`BillionsOfExperience` bigint NOT NULL,
	`MillionsOfExperience` bigint NOT NULL,
	`Nothing6` smallint NOT NULL,
	`Spell0` smallint NOT NULL,
	`Spell1` smallint NOT NULL,
	`Spell2` smallint NOT NULL,
	`Spell3` smallint NOT NULL,
	`Spell4` smallint NOT NULL,
	`Spell5` smallint NOT NULL,
	`Spell6` smallint NOT NULL,
	`Spell7` smallint NOT NULL,
	`Spell8` smallint NOT NULL,
	`Spell9` smallint NOT NULL,
	`Spell10` smallint NOT NULL,
	`Spell11` smallint NOT NULL,
	`Spell12` smallint NOT NULL,
	`Spell13` smallint NOT NULL,
	`Spell14` smallint NOT NULL,
	`Spell15` smallint NOT NULL,
	`Spell16` smallint NOT NULL,
	`Spell17` smallint NOT NULL,
	`Spell18` smallint NOT NULL,
	`Spell19` smallint NOT NULL,
	`Spell20` smallint NOT NULL,
	`Spell21` smallint NOT NULL,
	`Spell22` smallint NOT NULL,
	`Spell23` smallint NOT NULL,
	`Spell24` smallint NOT NULL,
	`Spell25` smallint NOT NULL,
	`Spell26` smallint NOT NULL,
	`Spell27` smallint NOT NULL,
	`Spell28` smallint NOT NULL,
	`Spell29` smallint NOT NULL,
	`Spell30` smallint NOT NULL,
	`Spell31` smallint NOT NULL,
	`Spell32` smallint NOT NULL,
	`Spell33` smallint NOT NULL,
	`Spell34` smallint NOT NULL,
	`Spell35` smallint NOT NULL,
	`Spell36` smallint NOT NULL,
	`Spell37` smallint NOT NULL,
	`Spell38` smallint NOT NULL, 
	`Spell39` smallint NOT NULL,
	`Spell40` smallint NOT NULL,
	`Spell41` smallint NOT NULL,
	`Spell42` smallint NOT NULL,
	`Spell43` smallint NOT NULL,
	`Spell44` smallint NOT NULL,
	`Spell45` smallint NOT NULL,
	`Spell46` smallint NOT NULL,
	`Spell47` smallint NOT NULL,
	`Spell48` smallint NOT NULL,
	`Spell49` smallint NOT NULL,
	`Spell50` smallint NOT NULL,
	`Spell51` smallint NOT NULL,
	`Spell52` smallint NOT NULL,
	`Spell53` smallint NOT NULL,
	`Spell54` smallint NOT NULL,
	`Spell55` smallint NOT NULL,
	`Spell56` smallint NOT NULL,
	`Spell57` smallint NOT NULL,
	`Spell58` smallint NOT NULL,
	`Spell59` smallint NOT NULL,
	`Spell60` smallint NOT NULL,
	`Spell61` smallint NOT NULL,
	`Spell62` smallint NOT NULL,
	`Spell63` smallint NOT NULL,
	`Spell64` smallint NOT NULL,
	`Spell65` smallint NOT NULL,
	`Spell66` smallint NOT NULL,
	`Spell67` smallint NOT NULL,
	`Spell68` smallint NOT NULL,
	`Spell69` smallint NOT NULL,
	`Spell70` smallint NOT NULL,
	`Spell71` smallint NOT NULL,
	`Spell72` smallint NOT NULL,
	`Spell73` smallint NOT NULL,
	`Spell74` smallint NOT NULL,
	`Spell75` smallint NOT NULL,
	`Spell76` smallint NOT NULL,
	`Spell77` smallint NOT NULL,
	`Spell78` smallint NOT NULL,
	`Spell79` smallint NOT NULL,
	`Spell80` smallint NOT NULL,
	`Spell81` smallint NOT NULL,
	`Spell82` smallint NOT NULL,
	`Spell83` smallint NOT NULL,
	`Spell84` smallint NOT NULL,
	`Spell85` smallint NOT NULL,
	`Spell86` smallint NOT NULL,
	`Spell87` smallint NOT NULL,
	`Spell88` smallint NOT NULL,
	`Spell89` smallint NOT NULL,
	`Spell90` smallint NOT NULL,
	`Spell91` smallint NOT NULL,
	`Spell92` smallint NOT NULL,
	`Spell93` smallint NOT NULL,
	`Spell94` smallint NOT NULL,
	`Spell95` smallint NOT NULL,
	`Spell96` smallint NOT NULL,
	`Spell97` smallint NOT NULL,
	`Spell98` smallint NOT NULL,
	`Spell99` smallint NOT NULL,
	`EvilPoints` smallint NOT NULL,
	`nothing71` int NOT NULL,
	`nothing72` int NOT NULL,
	`nothing73` int NOT NULL,
	`LastMap0` int NOT NULL,
	`LastMap1` int NOT NULL,
	`LastMap2` int NOT NULL,
	`LastMap3` int NOT NULL,
	`LastMap4` int NOT NULL,
	`LastMap5` int NOT NULL,
	`LastMap6` int NOT NULL,
	`LastMap7` int NOT NULL,
	`LastMap8` int NOT NULL,
	`LastMap9` int NOT NULL,
	`LastMap10` int NOT NULL,
	`LastMap11` int NOT NULL,
	`LastMap12` int NOT NULL,
	`LastMap13` int NOT NULL,
	`LastMap14` int NOT NULL,
	`LastMap15` int NOT NULL,
	`LastMap16` int NOT NULL,
	`LastMap17` int NOT NULL,
	`LastMap18` int NOT NULL,
	`LastMap19` int NOT NULL,
	`LastRoom0` int NOT NULL,
	`LastRoom1` int NOT NULL,
	`LastRoom2` int NOT NULL,
	`LastRoom3` int NOT NULL,
	`LastRoom4` int NOT NULL,
	`LastRoom5` int NOT NULL,
	`LastRoom6` int NOT NULL,
	`LastRoom7` int NOT NULL,
	`LastRoom8` int NOT NULL,
	`LastRoom9` int NOT NULL,
	`LastRoom10` int NOT NULL,
	`LastRoom11` int NOT NULL,
	`LastRoom12` int NOT NULL,
	`LastRoom13` int NOT NULL,
	`LastRoom14` int NOT NULL,
	`LastRoom15` int NOT NULL,
	`LastRoom16` int NOT NULL,
	`LastRoom17` int NOT NULL,
	`LastRoom18` int NOT NULL,
	`LastRoom19` int NOT NULL,
	`nothing8` smallint NOT NULL,
	`BroadcastChan` smallint NOT NULL,
	`unknown5` int NOT NULL,
	`Perception` smallint NOT NULL,
	`Stealth` smallint NOT NULL,
	`MartialArts` smallint NOT NULL,
	`Thievery` smallint NOT NULL,
	`ManaMax` smallint NOT NULL,
	`ManaCurr` smallint NOT NULL,
	`SpellCasting` smallint NOT NULL,
	`Traps` smallint NOT NULL,
	`unknown6` smallint NOT NULL,
	`Picklocks` smallint NOT NULL,
	`Tracking` smallint NOT NULL,
	`nothing9` smallint NOT NULL,
	`Runic` int NOT NULL,
	`Platinum` int NOT NULL,
	`Gold` int NOT NULL,
	`Silver` int NOT NULL,
	`Copper` int NOT NULL,
	`WornWeapon` int NOT NULL,
	`nothing10` int NOT NULL,
	`WornItem0` int NOT NULL,
	`WornItem1` int NOT NULL,
	`WornItem2` int NOT NULL,
	`WornItem3` int NOT NULL,
	`WornItem4` int NOT NULL,
	`WornItem5` int NOT NULL,
	`WornItem6` int NOT NULL,
	`WornItem7` int NOT NULL,
	`WornItem8` int NOT NULL,
	`WornItem9` int NOT NULL,
	`WornItem10` int NOT NULL,
	`WornItem11` int NOT NULL,
	`WornItem12` int NOT NULL,
	`WornItem13` int NOT NULL,
	`WornItem14` int NOT NULL,
	`WornItem15` int NOT NULL,
	`WornItem16` int NOT NULL,
	`WornItem17` int NOT NULL,
	`WornItem18` int NOT NULL,
	`WornItem19` int NOT NULL,
	`unknown71` smallint NOT NULL,
	`unknown72` smallint NOT NULL,
	`unknown73` smallint NOT NULL,
	`unknown74` smallint NOT NULL,
	`unknown75` smallint NOT NULL,
	`unknown76` smallint NOT NULL,
	`unknown77` smallint NOT NULL,
	`unknown78` smallint NOT NULL,
	`unknown79` smallint NOT NULL,
	`unknown710` smallint NOT NULL,
	`unknown711` smallint NOT NULL,
	`unknown712` smallint NOT NULL,
	`unknown713` smallint NOT NULL,
	`unknown714` smallint NOT NULL,
	`unknown715` smallint NOT NULL,
	`unknown716` smallint NOT NULL,
	`unknown717` smallint NOT NULL,
	`unknown718` smallint NOT NULL,
	`unknown719` smallint NOT NULL,
	`unknown720` smallint NOT NULL,
	`unknown8` smallint NOT NULL,
	`LivesRemaining` smallint NOT NULL,
	`unknown91` smallint NOT NULL,
	`unknown92` smallint NOT NULL,
	`unknown93` smallint NOT NULL,
	`unknown94` smallint NOT NULL,
	`unknown95` smallint NOT NULL,
	`unknown96` smallint NOT NULL,
	`unknown97` smallint NOT NULL,
	`unknown98` smallint NOT NULL,
	`unknown99` smallint NOT NULL,
	`unknown910` smallint NOT NULL,
	`unknown911` smallint NOT NULL,
	`unknown912` smallint NOT NULL,
	`unknown913` smallint NOT NULL,
	`unknown914` smallint NOT NULL,
	`unknown915` smallint NOT NULL,
	`unknown916` smallint NOT NULL,
	`GangName` varchar(19) NOT NULL,
	`unknown111` tinyint NOT NULL,
	`unknown112` tinyint NOT NULL,
	`unknown113` tinyint NOT NULL,
	`unknown114` tinyint NOT NULL,
	`unknown115` tinyint NOT NULL,
	`unknown116` tinyint NOT NULL,
	`CPRemaining` smallint NOT NULL,
	`SuicidePassword` varchar(7) NOT NULL,
	`unknown12a1` smallint NOT NULL,
	`unknown12a2` smallint NOT NULL,
	`unknown12a3` smallint NOT NULL,
	`unknown12a4` smallint NOT NULL,
	`unknown12a5` smallint NOT NULL,
	`unknown12a6` smallint NOT NULL,
	`unknown12a7` smallint NOT NULL,
	`unknown12a8` smallint NOT NULL,
	`bEDITED` tinyint NOT NULL,
	`unknown12c` tinyint NOT NULL,
	`unknown12d1` smallint NOT NULL,
	`unknown12d2` smallint NOT NULL,
	`unknown12d3` smallint NOT NULL,
	`unknown12d4` smallint NOT NULL,
	`unknown12d5` smallint NOT NULL,
	`unknown12d6` smallint NOT NULL,
	`unknown12d7` smallint NOT NULL,
	`unknown12d8` smallint NOT NULL,
	`unknown12d9` smallint NOT NULL,
	`unknown12d10` smallint NOT NULL,
	`unknown12d11` smallint NOT NULL,
	`unknown12d12` smallint NOT NULL,
	`unknown12d13` smallint NOT NULL,
	`unknown12d14` smallint NOT NULL,
	`unknown12d15` smallint NOT NULL,
	`unknown12d16` smallint NOT NULL,
	`unknown12d17` smallint NOT NULL,
	`unknown12d18` smallint NOT NULL,
	`unknown12d19` smallint NOT NULL,
	`unknown12d20` smallint NOT NULL,
	`unknown12d21` smallint NOT NULL,
	`unknown12d22` smallint NOT NULL,
	`unknown12d23` smallint NOT NULL,
	`unknown12d24` smallint NOT NULL,
	`unknown12d25` smallint NOT NULL,
	`unknown12d26` smallint NOT NULL,
	`unknown12d27` smallint NOT NULL,
	`unknown12d28` smallint NOT NULL,
	`unknown12d29` smallint NOT NULL,
	`unknown12d30` smallint NOT NULL,
	`Ability0` smallint NOT NULL,
	`Ability1` smallint NOT NULL,
	`Ability2` smallint NOT NULL,
	`Ability3` smallint NOT NULL,
	`Ability4` smallint NOT NULL,
	`Ability5` smallint NOT NULL,
	`Ability6` smallint NOT NULL,
	`Ability7` smallint NOT NULL,
	`Ability8` smallint NOT NULL,
	`Ability9` smallint NOT NULL,
	`Ability10` smallint NOT NULL,
	`Ability11` smallint NOT NULL,
	`Ability12` smallint NOT NULL,
	`Ability13` smallint NOT NULL,
	`Ability14` smallint NOT NULL,
	`Ability15` smallint NOT NULL,
	`Ability16` smallint NOT NULL,
	`Ability17` smallint NOT NULL,
	`Ability18` smallint NOT NULL,
	`Ability19` smallint NOT NULL,
	`Ability20` smallint NOT NULL,
	`Ability21` smallint NOT NULL,
	`Ability22` smallint NOT NULL,
	`Ability23` smallint NOT NULL,
	`Ability24` smallint NOT NULL,
	`Ability25` smallint NOT NULL,
	`Ability26` smallint NOT NULL,
	`Ability27` smallint NOT NULL,
	`Ability28` smallint NOT NULL,
	`Ability29` smallint NOT NULL,
	`AbilityModifier0` smallint NOT NULL,
	`AbilityModifier1` smallint NOT NULL,
	`AbilityModifier2` smallint NOT NULL,
	`AbilityModifier3` smallint NOT NULL,
	`AbilityModifier4` smallint NOT NULL,
	`AbilityModifier5` smallint NOT NULL,
	`AbilityModifier6` smallint NOT NULL,
	`AbilityModifier7` smallint NOT NULL,
	`AbilityModifier8` smallint NOT NULL,
	`AbilityModifier9` smallint NOT NULL,
	`AbilityModifier10` smallint NOT NULL,
	`AbilityModifier11` smallint NOT NULL,
	`AbilityModifier12` smallint NOT NULL,
	`AbilityModifier13` smallint NOT NULL,
	`AbilityModifier14` smallint NOT NULL,
	`AbilityModifier15` smallint NOT NULL,
	`AbilityModifier16` smallint NOT NULL,
	`AbilityModifier17` smallint NOT NULL,
	`AbilityModifier18` smallint NOT NULL,
	`AbilityModifier19` smallint NOT NULL,
	`AbilityModifier20` smallint NOT NULL,
	`AbilityModifier21` smallint NOT NULL,
	`AbilityModifier22` smallint NOT NULL,
	`AbilityModifier23` smallint NOT NULL,
	`AbilityModifier24` smallint NOT NULL,
	`AbilityModifier25` smallint NOT NULL,
	`AbilityModifier26` smallint NOT NULL,
	`AbilityModifier27` smallint NOT NULL,
	`AbilityModifier28` smallint NOT NULL,
	`AbilityModifier29` smallint NOT NULL,
	`unknown13a` smallint NOT NULL,
	`unknown13b` smallint NOT NULL,
	`unknown13c` smallint NOT NULL,
	`unknown13d` smallint NOT NULL,
	`unknown13e` smallint NOT NULL,
	`unknown13f` smallint NOT NULL,
	`unknown13g` smallint NOT NULL,
	`CharLife` int NOT NULL,
	`unknown131` smallint NOT NULL,
	`unknown132` smallint NOT NULL,
	`unknown133` smallint NOT NULL,
	`unknown134` smallint NOT NULL,
	`unknown135` smallint NOT NULL,
	`unknown136` smallint NOT NULL,
	`unknown137` smallint NOT NULL,
	`unknown138` smallint NOT NULL,
	`unknown139` smallint NOT NULL,
	`Bitmask1` tinyint NOT NULL,
	`Bitmask2` tinyint NOT NULL,
	`TestFlag1` tinyint NOT NULL,
	`TestFlag2` tinyint NOT NULL,
	`unknown14` smallint NOT NULL,
	`unknown151` int NOT NULL,
	`unknown152` int NOT NULL,
	`unknown153` int NOT NULL,
	`unknown154` int NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `BBSName` (`BBSName`),
	UNIQUE KEY `FirstName` (`FirstName`),
	KEY `GangName` (`GangName`),
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_general_ci;

--
-- Dumping data for table `abilities`
--

/*
	ANSI COLORS (hex => decimal)
	CONV('b4b4b4', 16, 10)

	normal  = #b4b4b4 => 11842740			white     = #dbdde4 => 14409188
	blue    = #3a57d7 => 3823575			h_blue    = #507cff => 5274879
	cyan    = #258f8f => 2461583			h_cyan    = #4dc5dc => 5096924
	green   = #1aaa13 => 1747475			h_green   = #5dce33 => 6147635
	grey    = #8c8b89 => 9210761			h_grey    = #aeaeae => 11447982
	magenta = #be007f => 12451967			h_magenta = #e671d3 => 15102419
	red     = #be1919 => 12458265			h_red     = #dc2f32 => 14430002
	yellow  = #ffaa3e => 16755262			h_yellow  = #fadd2d => 16440621

*/

LOCK TABLES `abilities` WRITE;
INSERT INTO `abilities` (`number`, `name`, `color`, `description`, `script_id`) VALUES
	(0, 'empty', 11842740, 'The "nothing" attribute. New objects automatically have their attributes filled with this.', 0),
	(1, 'Damage', 14430002, 'Does damage in the amount specified by the parameter. MR is not taken into account.', 6),
	(2, 'AC', 11842740, 'Modifies the AC value specified by the parameter, this AC is NOT affected by the targets weight. Used in barkskin and stoneskin.', 0),
	(3, 'Rcol', 5274879, 'Modifies resistance to cold by the value specified by the parameter.', 0),
	(4, 'Max Damage', 5096924, 'Modifies max damage to the value specified by the parameter.', 0),
	(5, 'Rfir', 14430002, 'Modifies resistance to fire by the value specified by the parameter.', 0),
	(6, 'Enslave', 6147635, 'Charms the target.', 0),
	(7, 'DR', 11842740, 'Modifies the DR value specified by the parameter. Note that DR is expressed in multiples of 10.', 0),
	(8, 'Drain', 14430002, 'Drains HP from the target to the caster. (usually seen in spells)', 0),
	(9, 'Shadow', 9210761, 'Displays "A shadowy figure!" when looked at by other players.', 0),
	(10, 'AC(Blur)', 5096924, 'Modifies the AC value specified by the parameter, this AC IS affected by the targets encumberance. Used in blur, and the spell for the amethyst pendant.', 0),
	(11, 'EnergyLevel', 2461583, 'Modifies the Energy level specified by the parameter.', 0),
	(12, 'Summon', 5274879, 'Summons a monster specified by the parameter. The value in parameter is the monster number.', 0),
	(13, 'Illu', 16440621, 'Increases or decreases the light value for the target ONLY by the value specified in the parameter.', 0),
	(14, 'RoomIllu', 16440621, 'Increases or decreases the light value for the entire room by the value specified in the parameter.', 0),
	(15, 'Alterhunger', 16755262, 'Unknown', 0),
	(16, 'Alter thirst', 16755262, 'Unknown', 0),
	(17, 'Damage(-MR)', 14430002, 'Does damage which takes into account the targets MR (or so the name implies).', 0),
	(18, 'Heal', 5096924, 'Heals damage specified by the value in the parameter.', 0),
	(19, 'Poison', 1747475, 'Poisons the target doing damage specified by the value in the parameter.', 0),
	(20, 'Cure Poison', 5096924, 'Cures poison (cure poison has a parameter of 8, as does antidote).', 0),
	(21, 'ImmuPoison', 1747475, 'Used in duration spells to make the target immune to poison.', 0),
	(22, 'Accuracy', 5096924, 'Increases the targets accuracy by the value specified in the parameter. (bless increases this value by 3, divine favour increases it by 10)', 0),
	(23, 'AffectsUndead', 11842740, 'Used to make a spell ONLY work on undead monsters.', 0),
	(24, 'ProtEvil', 14430002, 'Protection from evil.', 0),
	(25, 'ProtGood', 14409188, 'Protection from good.', 0),
	(26, 'DetectMagic', 5274879, 'Detects the magic in an item.', 0),
	(27, 'Stealth', 11842740, 'Modifies stealth by the value in the parameter.', 0),
	(28, 'Magical', 5274879, 'Defines the magical potency of an item. Witchunters cannot use items with this flag. To make a non-magical item hit highly magical creatures, use the HitMagic flag.', 0),
	(29, 'Punch', 14430002, 'Used in the Mystic class definition to grant the Punch ability. A parameter of +1 is used in their definition.', 0),
	(30, 'Kick', 14430002, 'Used in the Mystic class definition to grant the Kick ability. A parameter of +1 is used in their definition.', 0),
	(31, 'Bash', 14430002, 'Used in almost all class definition to grant the ability to bash attack monsters.', 0),
	(32, 'Smash', 14430002, 'Unknown', 0),
	(33, 'Killblow', 14430002, 'Unknown', 0),
	(34, 'Dodge', 2461583, 'Increases or decreases the targets ability to Dodge by the % value specified in the parameter.', 0),
	(35, 'JumpKick', 14430002, 'Used in the Mystic class definition to grant the JumpKick ability. A parameter of +1 is used in their definition.', 0),
	(36, 'M.R.', 5096924, 'Increases or decreases the targets MR by the value specified in the parameter.', 0),
	(37, 'Picklocks', 6147635, 'In Race and Class definitions, this grants the ability to Picklock, in items, this can be used to enhance the ability.', 0),
	(38, 'Tracking', 6147635, 'Used in Race and Class definitions to grant Tracking to a Race/Class.', 0),
	(39, 'Thievery', 1747475, 'In Race and Class definitions, this grants the ability to Rob, in items, this can be used to enhance the ability.', 0),
	(40, 'FindTraps', 1747475, 'In Race and Class definitions, this grants the ability to find traps, in items, this can be used to enhance the ability.', 0),
	(41, 'DisarmTraps', 1747475, 'In Race and Class definitions, this grants the ability to disarm traps, in items, this can be used to enhance the ability.', 0),
	(42, 'LearnSp', 5274879, 'Places the spell specified in the parameter into the players spells list. Also used for Kai powers and Bard songs. Use this in a\r\nscroll item. The parameter is the spell number.', 0),
	(43, 'CastsSp', 5274879, 'Casts the spell when an item is ''used'', or, with the %Spell attribute, this is the spell that is cast when the % chance is met.', 0),
	(44, 'Intel', 2461583, 'Increases or decreases the Intel stat by the value specified in the parameter.', 0),
	(45, 'Wisdom', 2461583, 'Increases or decreases the Wisdom/Willpower stat by the value specified in the parameter.', 0),
	(46, 'Strength', 2461583, 'Increases or decreases the Strength stat by the value specified in the parameter.', 0),
	(47, 'Health', 2461583, 'Increases or decreases the Health stat by the value specified in the parameter.', 0),
	(48, 'Agility', 2461583, 'Increases or decreases the Agility stat by the value specified in the parameter.', 0),
	(49, 'Charm', 2461583, 'Increases or decreases the Charm stat by the value specified in the parameter.', 0),
	(50, 'MageBaneQuest', 5096924, 'This Determines if the player has completed the MageBane quest.', 0),
	(51, 'AntiMagic', 14430002, 'Used in the Witchunter class definition, apperently the only effect being that MR effects beneficial as well as combat spells cast on the target.', 0),
	(52, 'EvilInCombat', 14430002, 'Used in spells to generate evil warnings and give EP when used.', 0),
	(53, 'BlindingLight', 14409188, 'Unknown', 0),
	(54, 'IlluTarget', 16440621, 'Increases or decreases the light level for the target specified by the value in the parameter.', 0),
	(55, 'AlterGeneralLightDuration', 16440621, 'Unknown', 0),
	(56, 'RechargeItem', 5274879, 'Unknown', 0),
	(57, 'SeeHidden', 16440621, 'Grants the ability to see hidden players. For monsters, this allows them to see hidden players and attack them while they are sneaking or hiding. The monster will also follow even if the player escapes and re-sneaks.', 0),
	(58, 'Crits', 12451967, 'Increases or decreases the targets critical hit chance by the value specified in the parameter.', 0),
	(59, 'ClassOk', 2461583, 'Used in items to make the item equippable by classes they aren''t intended to be used with.', 0),
	(60, 'Fear', 15102419, 'Makes the target flee in fear. Used in duration spells.', 0),
	(61, 'AffectExit', 14430002, 'Unknown', 0),
	(62, 'EvilChance', 9210761, 'Unknown', 0),
	(63, 'Experience', 9210761, 'Unknown (although one would assume this can be used to add/remove experience)', 0),
	(64, 'AddCP', 9210761, 'Unknown (although one would assume this can be used to add/remove CP)', 0),
	(65, 'ResistStone', 9210761, 'Modifies resistance to stone by the value specified by the parameter.', 0),
	(66, 'Rlit', 5096924, 'Modifies resistance to lightning by the value specified by the parameter.', 0),
	(67, 'Quickness', 15102419, 'does in fact make you walk faster (but only to a point so that it only matters if you''re heavy.)', 0),
	(68, 'Slowness', 14409188, 'Modifies the room movement time while not affecting stealth as a modified encumbrance would. The Mage spell "Slow" uses a parameter of +200 for this attribute.', 0),
	(69, 'MaxMana', 3823575, 'Increases or decreases the targets maximum mana by the value specified in the parameter.', 0),
	(70, 'S.C.', 5096924, 'Incresaes or decreases the targets SC by the value specified in the parameter.', 0),
	(71, 'Confusion', 15102419, 'Confuses the target, making them fumble in the % specified by the parameter. A parameter of +50 would make them fumble 50% of the time-- most "stun" spells use this with a value of +100, which makes the target fumble 100% of the time.', 0),
	(72, 'DamageShield', 3823575, 'Used to setup a shockshield for the player. Shockshield uses this.', 0),
	(73, 'DispellMagic', 3823575, 'cancels spells that affect the ability in the value (ie dispellmagic +107 cancels spells giving the "blind" ability), but probably only certain ones', 0),
	(74, 'HoldPerson', 14409188, 'Holds the target in the room. Used with duration spells. Entangle and Hold Person use this attribute.', 0),
	(75, 'Paralyze', 14409188, 'Unknown', 0),
	(76, 'Mute', 3823575, 'Strikes the target mute, making them unable to talk in rooms, etc.', 0),
	(77, 'Percep', 3823575, 'Increases or decreases the targets perception by the value specified in the parameter.', 0),
	(78, 'Animal', 6147635, 'Used in monster attributes to flag a monster as an animal. See "Affects Animals".', 0),
	(79, 'MageBind', 3823575, 'did use to make spellcasting impossible but not sure it''s still working.', 0),
	(80, 'AffectsAnimals', 6147635, 'Used in spells to make it ONLY affect animals.', 0),
	(81, 'Freedom', 5096924, 'Frees the target from holding spells and spells that alter the targets speed.', 0),
	(82, 'Cursed', 14430002, 'Used on items, once worn, a Cursed item can''t be removed.', 0),
	(83, 'CURSED', 14430002, 'has the same affects as 82 (curse) so you can''t remove an item but it also makes it not drop at death (unlike 82).. although the item is still unequipped at death so it kinda doesn''t work right.', 0),
	(84, 'Rcrs', 5096924, 'Remove curse. Seen in spells. The Priest spell "Remove Curse" uses this flag. Removes all cursed items.', 0),
	(85, 'Shatter', 3823575, 'Shatters the targets weapon. The parameter (in theory) specifies which "Quality" of weapons the spell affects and can shatter. The Druid sell "Shatter" specifies a parameter of 1, and thus will not work on items with a Quality of or greater than 1.', 0),
	(86, 'Quality', 3823575, 'Specifies an items "Quality". The only effect of this is to counter "Shatter". See "Shatter".', 0),
	(87, 'Speed', 3823575, 'Increases or decreases the targets swing speed with their weapon or attack by the value specified in the parameter. The Mage spell "Speed" uses +85 for a parameter, the Mage spell "Slow" uses +125.', 0),
	(88, 'Alter HP', 9210761, 'increases or decreases the targets max HP', 0),
	(89, 'PunchACY', 5096924, 'believed to alter punch accuracy value', 0),
	(90, 'KickACY', 5096924, 'believed to alter kick accuracy value', 0),
	(91, 'JumpKACY', 5096924, 'believed to alter jump accuracy value', 0),
	(92, 'PunchDmg', 14430002, 'Increases punch damage for the Mystic punch attack.', 0),
	(93, 'KickDmg', 14430002, 'Increases kick damage for the Mystic kick attack.', 0),
	(94, 'JumpKDmg', 14430002, 'Increases jumpkick damage for the Mystic jumpkick attack.', 0),
	(95, 'Slay', 12458265, 'Unknown. Used by the "laen longsword" item.', 0),
	(96, 'Encum', 3823575, 'Increases or decreases the targets encumberance % by the value specified in the parameter.', 0),
	(97, 'Good', 14409188, 'In spells and items, makes the spell/item useable only by Good aligned characters.', 0),
	(98, 'Evil', 14430002, 'In spells and items, makes the spell/item useable only by Evil aligned characters.', 0),
	(99, 'AlterDRpercent', 9210761, 'changes DR by the % in the value (is cast by some Mod 9 monsters with negative values.)', 0),
	(100, 'LoyalItem', 3823575, 'Makes the item stay with the player even into death. Seen in items.', 0),
	(101, 'ConfuseMsg', 12451967, 'Sets the confusion message for a previous "Confusion" attribute. The parameter specifies the message number to use for when the player is confused and fumbles. For the Mage spell "confusion", the message is along the lines of "You fumble in confusion!".', 0),
	(102, 'RaceStealth', 9210761, 'Used in Race definitions to grant racial stealth.', 0),
	(103, 'ClassStealth', 11842740, 'Used in Class definitions to grant class stealth.', 0),
	(104, 'DefenseModifier', 9210761, 'Unknown', 0),
	(105, 'Accuracy(2)', 14430002, 'Increases or decreases accuracy by the value specified in the parameter.', 0),
	(106, 'Accuracy (3)', 14430002, 'Increases or decreases accuracy by the value specified in the parameter.', 0),
	(107, 'BlindUser', 14430002, 'Blinds the target.', 0),
	(108, 'AffectsLiving', 14409188, 'Used in spells to limit their abilities to only living players or monsters. See "NonLiving"', 0),
	(109, 'NonLiving', 9210761, 'Used in monster attributes to flag the monster as being Non Living which makes it impossible to cast spells flagged as AffectsLiving on them. See "AffectsLiving"', 0),
	(110, 'NotGood', 14430002, 'Used in items/spells to flag the object as being useable by any alignment EXCEPT Good. (Neutral, Seedy, Outlaw, Criminal, Villain and FIEND can use it, but Good, Saint, Lawful cannot.)', 0),
	(111, 'NotEvil', 14409188, 'Used in items/spells to flag the object as being useable by any alignment EXCEPT Evil. (Lawful, Saint, Good, Neutral and Seedy can use it, but Outlaw, Criminal, Villain and FIEND cannot.)', 0),
	(112, 'Neutral', 2461583, 'In spells and items, makes the spell/item useable only by Neutral aligned characters.', 0),
	(113, 'NotNeutral', 2461583, 'Used in items/spells to flag the object as being useable by any alignment EXCEPT Neutral. (Lawful, Saint, Good, Outlaw, Criminal, Villain and FIEND can use it, but Neutral and Seedy cannot.)', 0),
	(114, '%Spell', 5274879, 'Used in items to make a "spell effect" occur on a percent chance on each hit or crit. The spell cast is specified by the NEXT "CastsSp" attribute. See "CastsSp".', 0),
	(115, 'DescMsg', 9210761, 'Used in spells. Specifies the message in WCCMSG.DAT to use when the spell wears off, when you are looked at, and when you type ''STAT'' to see the effect listed.', 0),
	(116, 'BSAccu', 12458265, 'Used in items (although I can see no reason why it couldn''t be used in a spell) to specify the backstab accuracy for the weapon. A positive value increases the chance to hit, a negative value decreases the chance to hit.', 0),
	(117, 'BsMinDmg', 3823575, 'Used in items (although I can see no reason why it couldn''t be used in a spell) to specify a higher (or lower) minimum backstab damage for the weapon when armed.', 0),
	(118, 'BsMaxDmg', 3823575, 'Used in items (although I can see no reason why it couldn''t be used in a spell) to specify a higher (or lower) maximum backstab damage for the weapon when armed.', 0),
	(119, 'Del@Maint', 14430002, 'Used in items to delete the item, hidden or not, at cleanup.', 0),
	(120, 'StartMsg', 3823575, 'Used in spells to specify the ''start message'' for the spell.Basically, this sets the opening line for the spell before the Cast Message is sent.', 0),
	(121, 'Recharge', 3823575, 'Used in items to specify the amount of "uses" to recharge at cleanup.', 0),
	(122, 'RemovesSpell', 5274879, 'Used in spells to remove other spells (cancel them out).', 0),
	(123, 'HPRegen', 14409188, 'Used in any object to modify the targets HP regen rate. The Druid spell "Rapid Healing" and the module-1 quest rings use this attribute.', 0),
	(124, 'NegateAbility', 9210761, 'Removes the ability number?', 0),
	(125, 'IceSorcQuest', 5096924, 'This is the progress the player has made with the Ice Sorceress quest.', 0),
	(126, 'GoodQuest', 14409188, 'This is the progress the player has made with the GOOD quest.', 0),
	(127, 'NeutralQuest', 2461583, 'This is the progress the player has made with the NEUTRAL quest.', 0),
	(128, 'EvilQuest', 14430002, 'This is the progress the player has made with the EVIL quest.', 0),
	(129, 'DarkDruidQuest', 5096924, 'This is the progress the player has made with the Dark Druid quest.', 0),
	(130, 'BloodChampQuest', 5096924, 'This is the progress the player has made with the Blood Champion quest.', 0),
	(131, 'SheDragonQuest', 5096924, 'This is the progress the player has made with the SheDragon quest.', 0),
	(132, 'WereratQuest', 5096924, 'This is the progress the player has made with the Wererat quest.', 0),
	(133, 'PhoenixQuest', 5096924, 'This is the progress the player has made with the Phoenix feather quest.', 0),
	(134, 'DaoLordQuest', 5096924, 'This is the progress the player has made with the DaoLord quest.', 0),
	(135, 'MinLevel', 14409188, 'Typically seen in items (useless for spells since they have their own internal Minimum level field) to restrict them to players ONLY of the level specified or higher. The value in the parameter is the minimum level.', 0),
	(136, 'MaxLevel', 14409188, 'Typically seen in items to restrict them to players ONLY of the level specified or LOWER. The value in the parameter is the maximum level.', 0),
	(137, 'Shock', 14430002, 'Sets the Shockshield message for the spell/item. See "DmgShield".', 0),
	(138, 'RoomVisible', 2461583, 'Makes the item visible to the entire room.', 0),
	(139, 'SpellImmu', 14430002, 'Used in objects to make the target immune to spells below or equal to the level specified in the parameter.', 0),
	(140, 'TeleportRoom', 15102419, 'Teleports the target to the specified room in the parameter. Usually seen with a "Teleport map". See "Teleport map".', 0),
	(141, 'TeleportMap', 12451967, 'Teleports the target to the specified map in the parameter. Usually seen with a "Teleport room". See "Teleport room".', 0),
	(142, 'HitMagic', 14430002, 'Seen in weapons (and possibly could be used in spells) and used to make them hit magical creatures of the value specified in the parameter or LOWER. HitMagic +5 for example would let the target hit monsters with a magical attribute of 5 or lower.', 0),
	(143, 'ClearItem', 9210761, 'Poofs or unequips item number?', 0),
	(144, 'NonMagicalSpell', 9210761, 'Flags the spell as non-magical, thus making it immune to MR.', 0),
	(145, 'ManaRgn', 12451967, 'Used in objects to increase or decrease the targets mana regen by the percent specified in the parameter. A value of +25 would increase the targets mana regen by 25%. A value of +100 would increase the targets mana regen by 100% (double).', 0),
	(146, 'MonsGuards', 14430002, 'Used in monster definitions to define a monster that protects this one. The parameter points to an entry in the monster database that will protect this one. Multiple MonsGuards can be used to make the monster be protected by different monsters.', 0),
	(147, 'ResistWater', 5274879, 'Increases or decreases the targets resistance to Water by the value specified in the parameter.', 0),
	(148, 'TextBlock', 2461583, 'Executes the text block specified by the parameter.', 0),
	(149, 'Remove@Maint', 14430002, 'Used in items-- removes the item at cleanup, poofing it.', 0),
	(150, 'HealMana', 5096924, 'Regenerates mana back by the value specified in the parameter.', 0),
	(151, 'EndCast', 5274879, 'Used in spell definitions to chain to another spell at the end of the current ones cast. EndCast is only called if the first spell doesn''t fail.', 0),
	(152, 'Rune', 5096924, 'Flags the object as a Rune. Seen in one item.', 0),
	(153, 'KillSpell', 5096924, 'Kills a spell without calling it''s EndCast effect (if one exists).', 0),
	(154, 'Visible@Maint', 5096924, 'Used in items to keep them visible at cleanup.', 0),
	(155, 'DeathText', 9210761, 'Unknown (executes the specified text block when the player dies?)', 0),
	(156, 'QuestItem', 3823575, 'Makes the item a quest item', 0),
	(157, 'ScatterItems', 14430002, 'Scatters the items in the room to the specified room(s). You can use a range to specify multiple rooms, but, these rooms must all be a part of the current map.', 0),
	(158, 'ReqToHit', 14430002, 'Monsters with this flag require that weapons (and spells?) with this IDENTICAL flag (including parameter) be used to attack it. NOTHING else will work on these monsters.', 0),
	(159, 'KaiBind', 5096924, 'Prevents the target from using Kai powers. Seen in 1.1u''s race change to Half-Ogre''s.', 0),
	(160, 'GiveTempSpell', 14409188, 'Unknown (gives the spell specified in Value/Parameter temporarily, as in, it appears in the spells/powers list? Maybe used in future items to give out spells only if a player has a specific item or has a specific item armed/equipped?)', 0),
	(161, 'OpenDoor', 14409188, 'Unknown (opens a door, I assume, but how it determines direction/etc is unknown)', 0),
	(162, 'Lore', 3823575, 'Unknown', 0),
	(163, 'SpellComponent', 5274879, 'Make the item a spell component.', 0),
	(164, 'CastOnEnd%', 5274879, 'cast a spell specificed in the next EndCast ability when this spell ends only Value % chance of the time', 0),
	(165, 'AlterSpDmg', 15102419, 'Unknown (alter spells damage (eg: used in an item or another spell to temporarily increase all spells damage)?)', 0),
	(166, 'AlterSpLength', 15102419, 'Unknown (alter the length of duration spells (eg: used in an item or another spell to temporarily increase all future spells durations)?)', 0),
	(167, 'UnEquipItem', 12451967, 'Unknown (remove either the specific item, or, perhaps the value is an item location? (head, arms, etc)?)', 0),
	(168, 'EquipItem', 15102419, 'Unknown (equip either the specific item, or, perhaps the value is an item location? (head, arms, etc)? and the first elgible item found in the players inventory is used?)', 0),
	(169, 'CannotWearLocation', 12451967, 'Unknown (perhaps used to make an item that can be worn on multiple locations, but, this flag is used to define WHICH locations it cannot be used on?)', 0),
	(170, 'Sleep', 12451967, 'Unknown', 0),
	(171, 'Invisibility', 12451967, 'Unknown (some new form of stealth perhaps that doesn''t rely on Stealth?)', 0),
	(172, 'SeeInvisible', 5096924, 'Unknown (most likely a way for monsters/players to see others with this new Invisible ability)', 0),
	(173, 'Scry', 5096924, 'Unknown (perhaps show the room specificed in the value? No idea really)', 0),
	(174, 'StealMana', 12458265, 'Unknown (most likely steals Mana from another Player or monster for the value specified (or min/max in a spell))', 0),
	(175, 'StealHPtoMP', 12458265, 'Unknown (convert stolen HP to Mana instead? Works like the other ''Steal'' abilities?)', 0),
	(176, 'StealMPtoHP', 12458265, 'Unknown (convert stolen Mana to HP instead? Works like the other ''Steal'' abilities?)', 0),
	(177, 'SpellColours', 15102419, 'Unknown (perhaps a way to specific the ANSI colour coding for spells, overriding the default colours for the spell?)', 0),
	(178, 'Shadowform', 9210761, 'This functions much like shadowform except the value states which text block to display when the player is looked at.', 0),
	(179, 'FindTrapsValue', 1747475, 'alters user''s Traps Value', 0),
	(180, 'PickLocksValue', 1747475, 'alters user''s PickLocks Value', 0),
	(181, 'GHouseDeed', 3823575, 'Gang House Deed value', 0),
	(182, 'GHouseTax', 3823575, 'Gang House Tax value', 0),
	(183, 'GHouseItem', 3823575, 'Gang House Item', 0),
	(184, 'GShopItem', 3823575, 'Gang Shop Item (controller)', 0),
	(185, 'BadAttk', 12458265, 'Do not Attack if Item Nmbr', 0),
	(186, 'PerStealth', 5096924, 'Perfect Stealth', 0),
	(187, 'Meditate', 5096924, 'Meditate skill granted', 0);
UNLOCK TABLES;
